### ISSUE TITLE
How to run the web editor with content assist?

### ISSUE THREAD

**Issue by hristo-vrigazov** [eclipse/xtext#1125]
I have a fresh Eclipse Oxygen install and created a new Xtext project with everything checked (including the web editor). I then generate Xtext artifact and verified that everything works in the newly started Eclipse. However, when I run the `ServletLauncher` class, it starts the server but when I type `Ctrl+Space` in the editor, nothing happens and the following stacktrace is dumped:
```

1) No implementation for org.eclipse.xtext.preferences.IPreferenceValuesProvider annotated with @org.eclipse.xtext.formatting2.FormatterPreferences() was bound.
  while locating org.eclipse.xtext.preferences.IPreferenceValuesProvider annotated with @org.eclipse.xtext.formatting2.FormatterPreferences()
    for field at org.eclipse.xtext.web.server.XtextServiceDispatcher.formatterPreferencesProvider(Unknown Source)
  while locating org.eclipse.xtext.web.server.XtextServiceDispatcher

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:961)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
	at org.eclipse.xtext.web.servlet.XtextServlet.getService(XtextServlet.java:162)
	at org.eclipse.xtext.web.servlet.XtextServlet.doPut(XtextServlet.java:122)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:710)
	at org.eclipse.xtext.web.servlet.XtextServlet.service(XtextServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:518)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)

[Thread-8] INFO org.eclipse.jetty.server.ServerConnector - Stopped ServerConnector@7b69c6ba{HTTP/1.1,[http/1.1]}{localhost:8080}
[Thread-8] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.w.WebAppContext@2c039ac6{/,file:///home/hvrigazov/workspace/bromium-dsl/com.hribol.bromium.dsl.parent/com.hribol.bromium.dsl.web/WebRoot/,UNAVAILABLE}
```

**Comment by cdietrich** [comment]
Hi, looks like you use an outdated xtext version: https://github.com/eclipse/xtext-web/issues/5

**Comment by hristo-vrigazov** [comment]
@cdietrich Yes, I am using 2.10.0, it was the newest in the release repository. I guess I should switch to Milestones repository?

**Comment by cdietrich** [comment]
which repo do you mean. xtext 2.11 and xtext 2.12 are released, the latter as part of oxygen

**Comment by kthoms** [comment]
No, the current release is 2.12. You should find it in the release repositories, e.g. Maven Central:
http://search.maven.org/#artifactdetails%7Corg.eclipse.xtext%7Corg.eclipse.xtext.web%7C2.12.0%7Cjar

**Comment by hristo-vrigazov** [comment]
@cdietrich @kthoms Sorry, I was just following the instructions here: https://eclipse.org/Xtext/download.html

**Comment by cdietrich** [comment]
this repo should give you Xtext 2.12 as well

**Comment by hristo-vrigazov** [comment]
@cdietrich Checked again and figured out why it happened. When I try to install it, the UI says "The installation cannot be completed as requested.", so it installed an older version. Now, I updated it through the milestones repo, but I get an error when I try to create a project:

![image](https://user-images.githubusercontent.com/14914140/29227989-b8a9a348-7ee0-11e7-9dc6-96d56d9e4430.png)

**Comment by cdietrich** [comment]
you should install 2.12, best directly from oxygen repo. have no idea why i cannot be installed. would need a detail message

**Comment by hristo-vrigazov** [comment]
Closing this as I reinstalled Oxygen again and it worked; I don't know what happened the first time. Anyway, since this was a well-known issue that's fixed, it's nothing to worry about, thanks for your time guys :) Oh and Xtext is great, I actually used it for university project some time ago and will now use it for my personal project
