### ISSUE TITLE
Xtext with Java10/Photon/Maven

### ISSUE THREAD

**Issue by DennisRoeck** [eclipse/xtext#1197]
Build of a example Project doesn't work with given configuration(Java10/Photon/Maven):
```
[INFO] Scanning for projects...
[ERROR] Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST C:\Users\dklassen\Eclipse\Photon_Xtext\eclipse\workspace\org.xtext.example.mydsl.parent\org.xtext.example.mydsl\META-INF\MANIFEST.MF: Unknown OSGi execution environment: 'JavaSE-10' -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST C:\Users\dklassen\Eclipse\Photon_Xtext\eclipse\workspace\org.xtext.example.mydsl.parent\org.xtext.example.mydsl\META-INF\MANIFEST.MF: Unknown OSGi execution environment: 'JavaSE-10'
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:120)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST C:\Users\dklassen\Eclipse\Photon_Xtext\eclipse\workspace\org.xtext.example.mydsl.parent\org.xtext.example.mydsl\META-INF\MANIFEST.MF: Unknown OSGi execution environment: 'JavaSE-10'
	at org.eclipse.tycho.core.osgitools.OsgiManifest.parseExecutionEnvironments(OsgiManifest.java:69)
	at org.eclipse.tycho.core.osgitools.OsgiManifest.<init>(OsgiManifest.java:55)
	at org.eclipse.tycho.core.osgitools.OsgiManifest.parse(OsgiManifest.java:152)
	at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifestFile(DefaultBundleReader.java:101)
	at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifestFromDirectory(DefaultBundleReader.java:97)
	at org.eclipse.tycho.core.osgitools.DefaultBundleReader.doLoadManifest(DefaultBundleReader.java:59)
	at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifest(DefaultBundleReader.java:50)
	at org.eclipse.tycho.core.osgitools.OsgiBundleProject.readArtifactKey(OsgiBundleProject.java:147)
	at org.eclipse.tycho.core.osgitools.OsgiBundleProject.setupProject(OsgiBundleProject.java:142)
	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.setupProject(DefaultTychoResolver.java:74)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:90)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:264)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	... 11 more
Caused by: org.eclipse.tycho.core.ee.UnknownEnvironmentException: Unknown OSGi execution environment: 'JavaSE-10'
	at org.eclipse.tycho.core.ee.ExecutionEnvironmentUtils.getExecutionEnvironment(ExecutionEnvironmentUtils.java:82)
	at org.eclipse.tycho.core.osgitools.OsgiManifest.parseExecutionEnvironments(OsgiManifest.java:66)
	... 24 more
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

**Comment by cdietrich** [comment]
you need a patched locally build tycho 1.2
snapshot for tycho.
i thought @kthoms told you that

in a java 8 shell:

```
git clone git://git.eclipse.org/gitroot/tycho/org.eclipse.tycho.git
cd org.eclipse.tycho
git fetch https://git.eclipse.org/r/tycho/org.eclipse.tycho refs/changes/69/121669/6 && git checkout FETCH_HEAD
mvn clean install -DskipTests
```

**Comment by kthoms** [comment]
No, did not tell that since I did not knew myself.

**Comment by cdietrich** [comment]
will only one tycho 1.2.0(-SNAPSHOT) is out

**Comment by cdietrich** [comment]
we will edit the release not depending on develoopment of the tycho issue
