### ISSUE TITLE
With new maven project there is no ecore-model generated.

### ISSUE THREAD

**Issue by DennisRoeck** [eclipse/xtext#1200]
0    [main] INFO  text.xtext.generator.XtextGenerator  - Initializing Xtext generator
16   [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Adding generated EPackage 'org.eclipse.xtext.common.types.TypesPackage'
370  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl at 'file:/C:/Users/dklassen/Eclipse/Photon_Xtext/eclipse/workspace/org.xtext.example.mydsl.parent/org.xtext.example.mydsl/'
372  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl.tests at 'file:/C:/Users/dklassen/Eclipse/Photon_Xtext/eclipse/workspace/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.tests/'
374  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl.ide at 'file:/C:/Users/dklassen/Eclipse/Photon_Xtext/eclipse/workspace/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.ide/'
376  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl.ui at 'file:/C:/Users/dklassen/Eclipse/Photon_Xtext/eclipse/workspace/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.ui/'
381  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl.ui.tests at 'file:/C:/Users/dklassen/Eclipse/Photon_Xtext/eclipse/workspace/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.ui.tests/'
393  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Using resourceSet registry. The registered Packages will not be registered in the global EPackage.Registry.INSTANCE!
664  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/Xtext/Xbase/XAnnotations' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
670  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/xbase/Xtype' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
695  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/xbase/Xbase' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
695  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/common/JavaVMTypes' from 'platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.genmodel'
1782 [main] INFO  erator.parser.antlr.AntlrToolFacade  - downloading file from 'http://download.itemis.com/antlr-generator-3.2.0-patch.jar' ...
4064 [main] INFO  erator.parser.antlr.AntlrToolFacade  - finished downloading.
4124 [main] INFO  text.xtext.generator.XtextGenerator  - Generating org.xtext.example.mydsl.MyDsl
5217 [main] INFO  nerator.ecore.EMFGeneratorFragment2  - Generating EMF model code
5434 [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.xtext.org/example/mydsl/MyDsl' from 'platform:/resource/org.xtext.example.mydsl/model/generated/MyDsl.genmodel'
5559 [main] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - org/eclipse/core/resources/IProjectNature
java.lang.NoClassDefFoundError: org/eclipse/core/resources/IProjectNature
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.emf.codegen.jet.JETCompiler.openStream(JETCompiler.java:873)
	at org.eclipse.emf.codegen.jet.JETCompiler.findLocation(JETCompiler.java:817)
	at org.eclipse.emf.codegen.jet.JETCompiler.find(JETCompiler.java:862)
	at org.eclipse.emf.codegen.ecore.genmodel.generator.GenModelGeneratorAdapterFactory.getMergeRulesURI(GenModelGeneratorAdapterFactory.java:263)
	at org.eclipse.emf.codegen.ecore.genmodel.generator.GenModelGeneratorAdapterFactory.initializeMergeRulesURI(GenModelGeneratorAdapterFactory.java:195)
	at org.eclipse.emf.codegen.ecore.genmodel.generator.GenModelGeneratorAdapterFactory.initialize(GenModelGeneratorAdapterFactory.java:168)
	at org.eclipse.emf.codegen.ecore.generator.Generator.initialize(Generator.java:285)
	at org.eclipse.emf.codegen.ecore.generator.Generator.setInput(Generator.java:254)
	at org.eclipse.xtext.xtext.generator.ecore.EMFGeneratorFragment2.doGenerate(EMFGeneratorFragment2.java:1001)
	at org.eclipse.xtext.xtext.generator.ecore.EMFGeneratorFragment2.generate(EMFGeneratorFragment2.java:457)
	at org.eclipse.xtext.xtext.generator.CompositeGeneratorFragment2.generate(CompositeGeneratorFragment2.java:50)
	at org.eclipse.xtext.xtext.generator.XtextGenerator.invokeInternal(XtextGenerator.java:230)
	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:126)
	at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.invoke(Mwe2Bridge.java:34)
	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:201)
	at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.invoke(AbstractCompositeWorkflowComponent.java:35)
	at org.eclipse.emf.mwe2.runtime.workflow.Workflow.run(Workflow.java:19)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:102)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:62)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:52)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
Caused by: java.lang.ClassNotFoundException: org.eclipse.core.resources.IProjectNature
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 46 more

0    [main] INFO  text.xtext.generator.XtextGenerator  - Initializing Xtext generator
16   [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Adding generated EPackage 'org.eclipse.xtext.common.types.TypesPackage'
370  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl at 'file:/C:/Users/dklassen/Eclipse/Photon_Xtext/eclipse/workspace/org.xtext.example.mydsl.parent/org.xtext.example.mydsl/'
372  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl.tests at 'file:/C:/Users/dklassen/Eclipse/Photon_Xtext/eclipse/workspace/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.tests/'
374  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl.ide at 'file:/C:/Users/dklassen/Eclipse/Photon_Xtext/eclipse/workspace/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.ide/'
376  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl.ui at 'file:/C:/Users/dklassen/Eclipse/Photon_Xtext/eclipse/workspace/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.ui/'
381  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl.ui.tests at 'file:/C:/Users/dklassen/Eclipse/Photon_Xtext/eclipse/workspace/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.ui.tests/'
393  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Using resourceSet registry. The registered Packages will not be registered in the global EPackage.Registry.INSTANCE!
664  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/Xtext/Xbase/XAnnotations' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
670  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/xbase/Xtype' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
695  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/xbase/Xbase' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
695  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/common/JavaVMTypes' from 'platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.genmodel'
1782 [main] INFO  erator.parser.antlr.AntlrToolFacade  - downloading file from 'http://download.itemis.com/antlr-generator-3.2.0-patch.jar' ...
4064 [main] INFO  erator.parser.antlr.AntlrToolFacade  - finished downloading.
4124 [main] INFO  text.xtext.generator.XtextGenerator  - Generating org.xtext.example.mydsl.MyDsl
5217 [main] INFO  nerator.ecore.EMFGeneratorFragment2  - Generating EMF model code
5434 [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.xtext.org/example/mydsl/MyDsl' from 'platform:/resource/org.xtext.example.mydsl/model/generated/MyDsl.genmodel'
5559 [main] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - org/eclipse/core/resources/IProjectNature
java.lang.NoClassDefFoundError: org/eclipse/core/resources/IProjectNature
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.emf.codegen.jet.JETCompiler.openStream(JETCompiler.java:873)
	at org.eclipse.emf.codegen.jet.JETCompiler.findLocation(JETCompiler.java:817)
	at org.eclipse.emf.codegen.jet.JETCompiler.find(JETCompiler.java:862)
	at org.eclipse.emf.codegen.ecore.genmodel.generator.GenModelGeneratorAdapterFactory.getMergeRulesURI(GenModelGeneratorAdapterFactory.java:263)
	at org.eclipse.emf.codegen.ecore.genmodel.generator.GenModelGeneratorAdapterFactory.initializeMergeRulesURI(GenModelGeneratorAdapterFactory.java:195)
	at org.eclipse.emf.codegen.ecore.genmodel.generator.GenModelGeneratorAdapterFactory.initialize(GenModelGeneratorAdapterFactory.java:168)
	at org.eclipse.emf.codegen.ecore.generator.Generator.initialize(Generator.java:285)
	at org.eclipse.emf.codegen.ecore.generator.Generator.setInput(Generator.java:254)
	at org.eclipse.xtext.xtext.generator.ecore.EMFGeneratorFragment2.doGenerate(EMFGeneratorFragment2.java:1001)
	at org.eclipse.xtext.xtext.generator.ecore.EMFGeneratorFragment2.generate(EMFGeneratorFragment2.java:457)
	at org.eclipse.xtext.xtext.generator.CompositeGeneratorFragment2.generate(CompositeGeneratorFragment2.java:50)
	at org.eclipse.xtext.xtext.generator.XtextGenerator.invokeInternal(XtextGenerator.java:230)
	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:126)
	at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.invoke(Mwe2Bridge.java:34)
	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:201)
	at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.invoke(AbstractCompositeWorkflowComponent.java:35)
	at org.eclipse.emf.mwe2.runtime.workflow.Workflow.run(Workflow.java:19)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:102)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:62)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:52)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
Caused by: java.lang.ClassNotFoundException: org.eclipse.core.resources.IProjectNature
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 46 more

**Comment by cdietrich** [comment]
Hi,

it looks like your emf is too old or too new. i already had discussed this with @kthoms so i thought he would havbe you informed. in photon m6 there is this bad broken version

**Comment by cdietrich** [comment]
and: does the error happen in maven or in eclipse

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext-core/issues/658
https://bugs.eclipse.org/bugs/show_bug.cgi?id=532232
https://www.eclipse.org/forums/index.php/t/1092330/

**Comment by cdietrich** [comment]
@kthoms which emf nightly is on xtext nightly composite?

**Comment by kthoms** [comment]
The generated target def uses http://download.eclipse.org/releases/photon
org.eclipse.emf.ecore=2.14.0.v20180213-0937
Looks too old.

In http://download.eclipse.org/staging/photon there is a newer build:
org.eclipse.emf.ecore=2.14.0.v20180420-1131

=> For testing replace the photon p2 URL in the generated target def temporary. We can expect that it will work with photon release, and staging will be added to the photon composite with M7 next week.

**Comment by cdietrich** [comment]
needs to be analyzed
needs retesting when photon m7 is out

**Comment by cdietrich** [comment]
No Longer reproducibly with phonton m7 update site     
( EMF - Eclipse Modeling Framework SDK	2.14.0.v20180421-1151)
