### ISSUE TITLE
Maven + Java 10 + Junit 5 error

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1205]
```
!ENTRY org.eclipse.osgi 4 0 2018-05-11 17:41:43.643
!MESSAGE Application error
!STACK 1
org.apache.maven.surefire.util.SurefireReflectionException: java.util.ServiceConfigurationError: org.junit.platform.engine.TestEngine: org.junit.jupiter.engine.JupiterTestEngine not a subtype
    at org.apache.maven.surefire.util.ReflectionUtils.instantiateOneArg(ReflectionUtils.java:135)
    at org.apache.maven.surefire.booter.SurefireReflector.instantiateProvider(SurefireReflector.java:276)
    at org.apache.maven.surefire.booter.ProviderFactory.createProvider(ProviderFactory.java:113)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:81)
    at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:107)
    at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.run(HeadlessTestApplication.java:21)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
    at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1471)
Caused by: java.util.ServiceConfigurationError: org.junit.platform.engine.TestEngine: org.junit.jupiter.engine.JupiterTestEngine not a subtype
    at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:588)
    at java.base/java.util.ServiceLoader.access$200(ServiceLoader.java:390)
    at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1236)
    at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
    at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
    at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
    at org.junit.platform.launcher.core.DefaultLauncher.<init>(DefaultLauncher.java:55)
    at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:59)
    at org.junit.platform.surefire.provider.JUnitPlatformProvider.<init>(JUnitPlatformProvider.java:85)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
    at org.apache.maven.surefire.util.ReflectionUtils.instantiateOneArg(ReflectionUtils.java:131)
    ... 23 more
```

**Comment by cdietrich** [comment]
@kthoms any idea?

**Comment by cdietrich** [comment]
[issues_1205.zip](https://github.com/eclipse/xtext/files/1995980/issues_1205.zip)

**Comment by cdietrich** [comment]
problem does not happen with junit5 and java 8 and tycho 1.1 (and non stanging photon)

=> could be caused by tycho 1.2.0 state

**Comment by cdietrich** [comment]
created https://bugs.eclipse.org/bugs/show_bug.cgi?id=534587

**Comment by cdietrich** [comment]
@kthoms this is fixed now correct?

**Comment by churlinpr** [comment]
@cdietrich > did you ultimately find a setup where both maven execute the tests and Eclipse find them (Run As > JUnit Test) ? I'm using a pomless tycho build and cannot find a method that works for both. Having:

```
Require-Bundle: org.junit,
 org.junit.jupiter.api,
 org.junit.jupiter.engine,
 org.junit.jupiter.migrationsupport,
 org.junit.jupiter.params,
 org.junit.platform.commons,
 org.junit.platform.engine,
 org.junit.platform.launcher,
 org.junit.platform.runner,
 org.junit.platform.suite.api,
 org.hamcrest.core,
 org.opentest4j,
 org.apiguardian
```

works for Eclipse, but tycho requires:

```
Import-Package: org.junit,
 org.junit.jupiter.api
```

I tried tycho 1.3.0 and 1.4.0

**Comment by churlinpr** [comment]
Thanks @cdietrich! Looking at projects created by xtext, I found out that I was missing the JUnit library in my .classpath: `<classpathentry kind="con" path="org.eclipse.jdt.junit.JUNIT_CONTAINER/5"/>`

I now have "Run As > JUnit Test" that works within Eclipse and using the "Import-Package" above makes it work from maven.

For the record, modifying the .classpath should make this entry visible in Eclipse: [JUnit Container in Eclipse](https://i.imgur.com/67kURAo.png). This is done with the GUI as follows: [Add JUnit Container to Eclipse project](https://i.imgur.com/bOXK0Uu.png).
