### ISSUE TITLE
Metamodel name must not start with lower case

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1324]
```
grammar org.xtext.example.mydsl2.MyDsl with org.eclipse.xtext.common.Terminals

generate MyDsl "http://www.xtext.org/example/mydsl2/MyDsl"

Model:
	greetings+=Greeting*;
	
Greeting:
	'Hello' name=ID '!';
```

This raises a warning "Metamodel names should start with a lower case letter.", but when generating code this actually is a hard constraint and fails with IAE.

```
ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - Problems running workflow org.xtext.example.mydsl2.GenerateMyDsl: 
[ERROR]: GeneratorException: (Element: -UNKNOWN-; Reported by: XtextGenerator)
	 java.lang.IllegalArgumentException: Cannot determine the package name of 'org.xtext.example.mydsl2.MyDsl.MyDslPackage'. Please use the TypeReference(packageName, className) constructor
	at org.eclipse.xtext.xtext.generator.model.TypeReference.getPackageName(TypeReference.java:197)
	at org.eclipse.xtext.xtext.generator.model.TypeReference.<init>(TypeReference.java:100)
	at org.eclipse.xtext.xtext.generator.model.TypeReference.<init>(TypeReference.java:96)
	at org.eclipse.xtext.xtext.generator.model.TypeReference.<init>(TypeReference.java:92)
	at org.eclipse.xtext.xtext.generator.ecore.EMFGeneratorFragment2$3.appendTo(EMFGeneratorFragment2.java:572)
```

The severity should therefore be error and the message should contain "must".

**Comment by cdietrich** [comment]
@kthoms did you try this with a old style workflow?

**Comment by kthoms** [comment]
I'm migrating a project. It was working at least with the old workflow.

**Comment by cdietrich** [comment]
So we would leave it configurable and set default to error

**Comment by cdietrich** [comment]
i wonder if we can use `new(String packageName, String className) {`  in type reference as we do it in other places

**Comment by cdietrich** [comment]
preferred idea: calculate package and classname and use different constructor in TypeReference

**Comment by szarnekow** [comment]
See `org.eclipse.xtext.xtext.generator.ecore.EMFGeneratorFragment2.addProjectContributions(Grammar, List<EPackage>, ResourceSet)` where we create a new TypeReference
