### ISSUE TITLE
Pin Guava Versions in Manifests to 21

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1391]
to avoid

```
!ENTRY org.eclipse.core.jobs 4 2 2019-01-22 10:19:27.125
!MESSAGE An internal error occurred during: "XtextReconcilerJob".
!STACK 0
java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfUnchecked(Ljava/lang/Throwable;)V
	at org.eclipse.xtext.xbase.typesystem.internal.DefaultReentrantTypeResolver.reentrantResolve(DefaultReentrantTypeResolver.java:145)
	at org.eclipse.xtext.xbase.typesystem.internal.CompoundReentrantTypeResolver.reentrantResolve(CompoundReentrantTypeResolver.java:79)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$LazyResolvedTypes.resolveTypes(CachingBatchTypeResolver.java:80)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$2.process(CachingBatchTypeResolver.java:57)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$2.process(CachingBatchTypeResolver.java:53)
	at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:37)
	at org.eclipse.xtext.util.OnChangeEvictingCache.execWithoutCacheClear(OnChangeEvictingCache.java:128)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver.doResolveTypes(CachingBatchTypeResolver.java:53)
	at org.eclipse.xtext.xbase.typesystem.internal.AbstractBatchTypeResolver.resolveTypes(AbstractBatchTypeResolver.java:69)
```

**Comment by kthoms** [comment]
When 20 is the actual lower bound we need, then the Manifests should declare this. Was not aware that there is actually code in use that won't work on Guava 14, and also users did not report that so far. So it should be no prob to raise the lower bound.

**Comment by cdietrich** [comment]
well i am reporting this as "user"

**Comment by cdietrich** [comment]
and since orbit has no 20 and we cannot test against 20 => 21

**Comment by jpaw** [comment]
Does this relate to #1283 (MWE upgrade to 2.10.0)? The current master of MWE also still uses the range [14,22) for guava. For consistency, this change could depend on the MWE upgrade and also pinning MWE to use guava 21.0 as well.

**Comment by cdietrich** [comment]
ping @szarnekow

**Comment by szarnekow** [comment]
I don’t know enough about dependencies in mvn. For all the other required artifacts we do use this notation though: 21.0.0 - question is: what’s different with Guava?

**Comment by cdietrich** [comment]
i think the question is more: are you ok with using 21 here too?

**Comment by szarnekow** [comment]
Yes, absolutely!

**Comment by cdietrich** [comment]
Fixed

**Comment by sailingKieler** [comment]
Hey @cdietrich, I also just came along that problem in `v2.16.0` - thanks for fixing already!
