### ISSUE TITLE
parseResult is null in LanguageServerImpl for invalid script

### ISSUE THREAD

**Issue by PHameete** [eclipse/xtext#1570]
Hello, I have a question about a null pointer I get for a simple grammar in combination with the LSP:

```
grammar com.dsl.Test with org.eclipse.xtext.common.Terminals
import "http://www.eclipse.org/emf/2002/Ecore" as ecore
generate test "http://www.example.com/test"

Model:
	output=Output;
Expression:
	value=INT;
Output:
	'output' expr=Expression;
```

Now if I provide the following invalid script to the Language Server:
```
output 5
asfasfas
```

This results in the following error on the Language Server:

```
Caused by: java.lang.NullPointerException: parseResult is null
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory.create(ContentAssistContextFactory.java:129)
	at org.eclipse.xtext.ide.server.contentassist.ContentAssistService.createProposals(ContentAssistService.java:114)
	at org.eclipse.xtext.ide.server.contentassist.ContentAssistService.createCompletionList(ContentAssistService.java:80)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$completion$35(LanguageServerImpl.java:597)
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:334)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.completion(LanguageServerImpl.java:599)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$completion$34(LanguageServerImpl.java:578)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:37)
	... 4 more
```

This error is returned by the Language Server to my editor which then stops providing any services to the editor (no validation, content proposals, etc)

Is it possible to define in the syntax that the End of File is expected after the 'Output' rule? If yes, how? And can this help to ensure that the parser will always produce a parseResult so that above does not happen?

Thanks!

**Comment by szarnekow** [comment]
I tried your grammar with a small unit test:
```
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			output 5
			asfasfas
		''')
		Assertions.assertNotNull(result)
		val res = result.eResource as XtextResource
		Assertions.assertNotNull(res.parseResult)
	}
```

The parse is result is not null for this case. Could you please provide a self contained repro?

**Comment by PHameete** [comment]
Hi @szarnekow 

Thank you for taking your time to look at this. I must apologize because this was an error on my end. The EOF was an edge case causing an error in my custom syntax error message provider. This probably caused the parsing process to fail entirely resulting a null parse result.
