### ISSUE TITLE
Change API-DIFF Job to use default image

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1907]
Change API-DIFF Job to use default image instead of our custom

**Comment by cdietrich** [comment]
https://github.com/xtext/xtext-apidiff/blob/master/Jenkinsfile

**Comment by cdietrich** [comment]
@NicoPrediger any update here?

**Comment by cdietrich** [comment]
move to 2.26

**Comment by kthoms** [comment]
With the 'centos-7' agent we are running into https://bugs.eclipse.org/bugs/show_bug.cgi?id=564559

When the centos-7 image is configured custom the pod is restarted in an endless loop:
```
08:53:43  Created Pod: xtext/xtext-xtend-api-diff-6bw3g-b3qzn
08:53:43  [Normal][xtext/xtext-xtend-api-diff-6bw3g-b3qzn][Scheduled] Successfully assigned xtext-xtend-api-diff-6bw3g-b3qzn to osnode-16.eclipse.org
08:53:43  [Normal][xtext/xtext-xtend-api-diff-6bw3g-b3qzn][SuccessfulMountVolume] MountVolume.SetUp succeeded for volume "gradle" 
08:53:43  [Normal][xtext/xtext-xtend-api-diff-6bw3g-b3qzn][SuccessfulMountVolume] MountVolume.SetUp succeeded for volume "workspace-volume" 
08:53:43  [Normal][xtext/xtext-xtend-api-diff-6bw3g-b3qzn][SuccessfulMountVolume] MountVolume.SetUp succeeded for volume "volume-known-hosts" 
08:53:44  [Normal][xtext/xtext-xtend-api-diff-6bw3g-b3qzn][SuccessfulMountVolume] MountVolume.SetUp succeeded for volume "default-token-t46wf" 
08:53:46  [Normal][xtext/xtext-xtend-api-diff-6bw3g-b3qzn][Pulled] Container image "docker.io/eclipsecbi/jiro-agent-centos-7:remoting-4.5" already present on machine
08:53:47  [Normal][xtext/xtext-xtend-api-diff-6bw3g-b3qzn][Created] Created container
08:53:47  [Normal][xtext/xtext-xtend-api-diff-6bw3g-b3qzn][Started] Started container
08:53:47  [Normal][xtext/xtext-xtend-api-diff-6bw3g-b3qzn][Pulled] Container image "docker.io/eclipsecbi/jiro-agent-basic:remoting-4.5" already present on machine
08:53:48  [Normal][xtext/xtext-xtend-api-diff-6bw3g-b3qzn][Created] Created container
08:53:48  [Normal][xtext/xtext-xtend-api-diff-6bw3g-b3qzn][Started] Started container
08:53:48  xtext/xtext-xtend-api-diff-6bw3g-b3qzn Container centos-7 was terminated (Exit Code: 0, Reason: Completed)
08:53:49  [Normal][xtext/xtext-xtend-api-diff-6bw3g-b3qzn][Killing] Killing container with id docker://jnlp:Need to kill Pod
08:54:03  Created Pod: xtext/xtext-xtend-api-diff-6bw3g-z0rmp
08:54:03  [Normal][xtext/xtext-xtend-api-diff-6bw3g-z0rmp][Scheduled] Successfully assigned xtext-xtend-api-diff-6bw3g-z0rmp to osnode-13.eclipse.org
08:54:03  [Normal][xtext/xtext-xtend-api-diff-6bw3g-z0rmp][SuccessfulMountVolume] MountVolume.SetUp succeeded for volume "gradle" 
08:54:03  [Normal][xtext/xtext-xtend-api-diff-6bw3g-z0rmp][SuccessfulMountVolume] MountVolume.SetUp succeeded for volume "workspace-volume" 
08:54:03  [Normal][xtext/xtext-xtend-api-diff-6bw3g-z0rmp][SuccessfulMountVolume] MountVolume.SetUp succeeded for volume "volume-known-hosts" 
08:54:03  [Normal][xtext/xtext-xtend-api-diff-6bw3g-z0rmp][SuccessfulMountVolume] MountVolume.SetUp succeeded for volume "default-token-t46wf" 
08:54:06  [Normal][xtext/xtext-xtend-api-diff-6bw3g-z0rmp][Pulled] Container image "docker.io/eclipsecbi/jiro-agent-centos-7:remoting-4.5" already present on machine
08:54:07  [Normal][xtext/xtext-xtend-api-diff-6bw3g-z0rmp][Created] Created container
08:54:07  [Normal][xtext/xtext-xtend-api-diff-6bw3g-z0rmp][Started] Started container
08:54:07  [Normal][xtext/xtext-xtend-api-diff-6bw3g-z0rmp][Pulled] Container image "docker.io/eclipsecbi/jiro-agent-basic:remoting-4.5" already present on machine
08:54:08  [Normal][xtext/xtext-xtend-api-diff-6bw3g-z0rmp][Created] Created container
08:54:09  [Normal][xtext/xtext-xtend-api-diff-6bw3g-z0rmp][Started] Started container
08:54:10  xtext/xtext-xtend-api-diff-6bw3g-z0rmp Container centos-7 was terminated (Exit Code: 0, Reason: Completed)
08:54:11  [Normal][xtext/xtext-xtend-api-diff-6bw3g-z0rmp][Killing] Killing container with id docker://jnlp:Need to kill Pod
```
Agent configuration was:
```
  agent {
    kubernetes {
      label 'xtext-xtend-api-diff'
      defaultContainer 'centos-7'
      yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: centos-7
    image: 'docker.io/eclipsecbi/jiro-agent-centos-7:remoting-4.5'
    args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
    resources:
      limits:
        memory: "3.5Gi"
        cpu: "1.0"
      requests:
        memory: "3.5Gi"
        cpu: "1.0"
    volumeMounts:
    - name: gradle
      mountPath: /home/jenkins/.gradle
  volumes:
  - name: volume-known-hosts
    configMap:
      name: known-hosts
  - name: gradle
    emptyDir: {}
    '''
    }
  }
```


Using the jnlp image runs into a Java 11 issue when executing the diff:
```
05:37:14  Exception in thread "main" java.lang.NoClassDefFoundError: javax.xml.bind.SchemaOutputResolver
05:37:14  	at de.dhuebner.japicmp.FolderComparator.createReport(FolderComparator.java:78)
05:37:14  	at de.dhuebner.japicmp.CheckFolder.main(CheckFolder.java:44)
05:37:14  Caused by: java.lang.ClassNotFoundException: javax.xml.bind.SchemaOutputResolver
05:37:14  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:766)
05:37:14  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
05:37:14  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1083)
05:37:14  	... 2 more
```

Agent configuration was:
```
  agent {
    kubernetes {
      label 'xtext-xtend-api-diff'
      defaultContainer 'jnlp'
      yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: 'eclipsecbi/jenkins-jnlp-agent'
    args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
    resources:
      limits:
        memory: "3.5Gi"
        cpu: "1.0"
      requests:
        memory: "3.5Gi"
        cpu: "1.0"
    volumeMounts:
    - name: gradle
      mountPath: /home/jenkins/.gradle
  volumes:
  - name: volume-known-hosts
    configMap:
      name: known-hosts
  - name: gradle
    emptyDir: {}
    '''
    }
  }
```

**Comment by cdietrich** [comment]
i assume it would work if we pull the java.xml.bind to the ius we install from orbit and the other repos
-installIU .....

**Comment by cdietrich** [comment]
done (for now)
