### ISSUE TITLE
xcore 'Unresolved compilation problem' on access to static member

### ISSUE THREAD

**Issue by richard-melvin** [eclipse/xtext#1963]
On Eclipse 21-03, create a new xcore project. 

In that project, create a simple java call `Hello` with a single static member:

```java
package dsl.demo;

public class Hello
{
  public static void world() {}
}

```

In the xcore file, import that class and call the member:

```

@Ecore(nsURI="http://www.scisys.org/StandaloneDemo")
@GenModel(modelName="StandaloneDemo")
package standalone.demo
import dsl.demo.Hello
class Entity {
    op void callHello() {
        Hello::world()
    }
}

```

In the editor, this shows up as a gray cross with no hover text:
![image](https://user-images.githubusercontent.com/5872490/113483207-2e718c80-949a-11eb-8ffe-f86e0fa6c2fa.png)

The generated code is:

```
  @Override
  public void callHello()
  {
    throw new Error("Unresolved compilation problems: Hello cannot be resolved to a type.");
  }
```

However, code generation works fine, if instead driven from maven.

**Comment by cdietrich** [comment]
@richard-melvin  can you please also share the project?

**Comment by richard-melvin** [comment]
[standalone.zip](https://github.com/eclipse/xtext/files/6263173/standalone.zip)

**Comment by richard-melvin** [comment]
also, on a clean build I get this erro stack trace:

```
eclipse.buildId=4.19.0.I20210303-1800
java.version=15.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product -data D:\workspaces\xtext_ws -product org.eclipse.epp.package.jee.product

org.apache.log4j
Error
Tue Apr 06 09:24:28 BST 2021
org.eclipse.xtext.xbase.resource.BatchLinkableResource  - Don't resolve expressions during indexing!


java.lang.IllegalStateException: Resource URI : platform:/resource/standalone/model/Reproduction.xcore, fragment : |3
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getEObject(BatchLinkableResource.java:117)
	at org.eclipse.emf.ecore.xcore.resource.XcoreResource.getEObject(XcoreResource.java:186)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:209)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:269)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eResolveProxy(BasicEObjectImpl.java:1516)
	at org.eclipse.xtext.xbase.impl.XAbstractFeatureCallImplCustom.getFeature(XAbstractFeatureCallImplCustom.java:49)
	at org.eclipse.xtext.xbase.impl.XAbstractFeatureCallImpl.eGet(XAbstractFeatureCallImpl.java:529)
	at org.eclipse.xtext.xbase.impl.XMemberFeatureCallImpl.eGet(XMemberFeatureCallImpl.java:474)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1050)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1042)
	at org.eclipse.emf.ecore.util.EContentsEList$FeatureIteratorImpl.hasNext(EContentsEList.java:439)
	at org.eclipse.emf.ecore.util.EcoreUtil$CrossReferencer.handleCrossReference(EcoreUtil.java:1802)
	at org.eclipse.emf.ecore.util.ECrossReferenceAdapter$InverseCrossReferencer.add(ECrossReferenceAdapter.java:336)
	at org.eclipse.emf.ecore.util.ECrossReferenceAdapter.setTarget(ECrossReferenceAdapter.java:983)
	at org.eclipse.emf.ecore.util.ECrossReferenceAdapter.setTarget(ECrossReferenceAdapter.java:965)
	at org.eclipse.emf.ecore.impl.MinimalEObjectImpl$1ArrayDelegatingAdapterList.didAdd(MinimalEObjectImpl.java:488)
	at org.eclipse.emf.ecore.impl.MinimalEObjectImpl$1ArrayDelegatingAdapterList.didAdd(MinimalEObjectImpl.java:1)
	at org.eclipse.emf.common.util.ArrayDelegatingEList.addUnique(ArrayDelegatingEList.java:389)
	at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:304)
	at org.eclipse.emf.ecore.util.ECrossReferenceAdapter.addAdapter(ECrossReferenceAdapter.java:1156)
	at org.eclipse.emf.ecore.util.ECrossReferenceAdapter.setTarget(ECrossReferenceAdapter.java:994)
	at org.eclipse.emf.ecore.util.ECrossReferenceAdapter.setTarget(ECrossReferenceAdapter.java:965)
	at org.eclipse.emf.ecore.impl.MinimalEObjectImpl$1ArrayDelegatingAdapterList.didAdd(MinimalEObjectImpl.java:488)
	at org.eclipse.emf.ecore.impl.MinimalEObjectImpl$1ArrayDelegatingAdapterList.didAdd(MinimalEObjectImpl.java:1)
	at org.eclipse.emf.common.util.ArrayDelegatingEList.addUnique(ArrayDelegatingEList.java:389)
	at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:304)
	at org.eclipse.emf.ecore.util.ECrossReferenceAdapter.addAdapter(ECrossReferenceAdapter.java:1156)
	at org.eclipse.emf.ecore.util.ECrossReferenceAdapter.setTarget(ECrossReferenceAdapter.java:994)
	at org.eclipse.emf.ecore.util.ECrossReferenceAdapter.setTarget(ECrossReferenceAdapter.java:965)
	at org.eclipse.emf.ecore.impl.MinimalEObjectImpl$1ArrayDelegatingAdapterList.didAdd(MinimalEObjectImpl.java:488)
	at org.eclipse.emf.ecore.impl.MinimalEObjectImpl$1ArrayDelegatingAdapterList.didAdd(MinimalEObjectImpl.java:1)
	at org.eclipse.emf.common.util.ArrayDelegatingEList.addUnique(ArrayDelegatingEList.java:389)
	at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:304)
	at org.eclipse.emf.ecore.util.ECrossReferenceAdapter.addAdapter(ECrossReferenceAdapter.java:1156)
	at org.eclipse.emf.ecore.util.ECrossReferenceAdapter.setTarget(ECrossReferenceAdapter.java:994)
	at org.eclipse.emf.ecore.util.ECrossReferenceAdapter.setTarget(ECrossReferenceAdapter.java:965)
	at org.eclipse.emf.ecore.impl.MinimalEObjectImpl$1ArrayDelegatingAdapterList.didAdd(MinimalEObjectImpl.java:488)
	at org.eclipse.emf.ecore.impl.MinimalEObjectImpl$1ArrayDelegatingAdapterList.didAdd(MinimalEObjectImpl.java:1)
	at org.eclipse.emf.common.util.ArrayDelegatingEList.addUnique(ArrayDelegatingEList.java:389)
	at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:304)
	at org.eclipse.emf.ecore.util.ECrossReferenceAdapter.addAdapter(ECrossReferenceAdapter.java:1156)
	at org.eclipse.emf.ecore.util.ECrossReferenceAdapter.setTarget(ECrossReferenceAdapter.java:994)
	at org.eclipse.emf.ecore.util.ECrossReferenceAdapter.setTarget(ECrossReferenceAdapter.java:965)
	at org.eclipse.emf.ecore.impl.MinimalEObjectImpl$1ArrayDelegatingAdapterList.didAdd(MinimalEObjectImpl.java:488)
	at org.eclipse.emf.ecore.impl.MinimalEObjectImpl$1ArrayDelegatingAdapterList.didAdd(MinimalEObjectImpl.java:1)
	at org.eclipse.emf.common.util.ArrayDelegatingEList.addUnique(ArrayDelegatingEList.java:389)
	at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:304)
	at org.eclipse.emf.ecore.util.ECrossReferenceAdapter.addAdapter(ECrossReferenceAdapter.java:1156)
	at org.eclipse.emf.ecore.util.ECrossReferenceAdapter.selfAdapt(ECrossReferenceAdapter.java:795)
	at org.eclipse.emf.ecore.util.ECrossReferenceAdapter.notifyChanged(ECrossReferenceAdapter.java:715)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1583)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1342)
	at org.eclipse.xtext.resource.persistence.StorageAwareResource.load(StorageAwareResource.java:64)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:266)
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:25)
	at org.eclipse.xtext.builder.resourceloader.SerialResourceLoader$1.next(SerialResourceLoader.java:48)
	at org.eclipse.xtext.builder.resourceloader.AbstractResourceLoader$CheckedLoadOperation.next(AbstractResourceLoader.java:81)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.writeNewResourceDescriptions(ClusteringBuilderState.java:379)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:140)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:164)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:388)
	at org.eclipse.xtext.builder.impl.XtextBuilder.addInfosFromTaskAndBuild(XtextBuilder.java:322)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:429)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:202)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:846)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:229)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:277)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:330)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:333)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:385)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:406)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)



```

**Comment by cdietrich** [comment]
hmm i also cannot reproduce it with your example. did you use DSL eclipse distro or did you build something up yourself?

**Comment by cdietrich** [comment]
of course no issues locally

**Comment by richard-melvin** [comment]
with a fresh install of 21-03 DSL tools package, I get:

```
Description	Resource	Path	Location	Type
Ecore cannot be resolved.	Reproduction.xcore	/standalone/model	line: 2 /standalone/model/Reproduction.xcore	Xcore Problem
GenModel cannot be resolved.	Reproduction.xcore	/standalone/model	line: 3 /standalone/model/Reproduction.xcore	Xcore Problem
The required library 'org.eclipse.emf.ecore.xcore.lib' isn't on the classpath	Reproduction.xcore	/standalone/model	line: 4 /standalone/model/Reproduction.xcore	Xcore Problem

```

**Comment by cdietrich** [comment]
Did you check the manifest

**Comment by richard-melvin** [comment]
It's not in the list of 'plugin- Dependencies' for the poject, but is in the 'Require-Bundle' that was generated by the wizard.
![image](https://user-images.githubusercontent.com/5872490/113709724-c067d800-96da-11eb-8cfc-1299112c8675.png)

**Comment by cdietrich** [comment]
how is your target platform configured?

**Comment by richard-melvin** [comment]
In the fresh installation,as the default:
![image](https://user-images.githubusercontent.com/5872490/113711929-6d435480-96dd-11eb-8dfc-c55c2eceb506.png)

**Comment by richard-melvin** [comment]
manifest and xcore erros are:
![image](https://user-images.githubusercontent.com/5872490/113712062-949a2180-96dd-11eb-9a3a-8e64ff4bab98.png)

**Comment by cdietrich** [comment]
the question is: is also the workspace a fresh one or npt.
what does the red error mark on the target platform say.
what happens if you hit reload

**Comment by richard-melvin** [comment]
![image](https://user-images.githubusercontent.com/5872490/113712434-07a39800-96de-11eb-97fc-d6eedac2ea55.png)

This is from a fresh eclipse install in a new directory (D:scratch/eclipse)

**Comment by cdietrich** [comment]
maybe an anitvirus or space or unpack problem

**Comment by richard-melvin** [comment]
yeah , switching to a fresh workspace and reimporting clear that issue at least.

**Comment by dhuebner** [comment]
@richard-melvin 
>  clear that issue at least.

I see any issues with your example project using eclipse 2021-03

```
Eclipse DSL Tools (includes Incubating components)
Version: 2021-03 (4.19.0)
```

**Comment by richard-melvin** [comment]
you mean 'don't see';?

**Comment by dhuebner** [comment]
@richard-melvin 
Yes, your example project works well with my eclipse 2021-03 DSL Package. No errors, generation works good.
Maybe you guys need professional Xtext support at SCISYS. Or is it your private project?

**Comment by richard-melvin** [comment]
yeah the standalone example now works for me with a fresh install, but the full project still doesn't. Only difference I can see is that the full project has xtext as an explciit plug-in dependency.
Probably not much you can so at your end; thanks for your help. I'll look into either paid support, or providing a better reproduction example.

**Comment by richard-melvin** [comment]
Changed a bunch of stuff and it works now, so closing as I don't think there is any real actionable bug.
