### ISSUE TITLE
Java Version for Xtext 2.15

### ISSUE THREAD

**Issue by Babwenbiber** [eclipse/xtext#1977]
I had to downgrade my Xtext Version from 2.25 to 2.15 because of some dependency issues within my project.
I managed to downgrade to 2.12, but I am also using JBase, so I needed to migrate to 2.15.
Now, I don't get anything to work.
When I get my Java Version >= 11 I get this issue #1316 and if I have Java 8 I have this issue #1976.
How can I solve this and get my project running again :)?

**Comment by cdietrich** [comment]
you should be able to use the workarounds stated in https://github.com/eclipse/xtext/issues/1976

**Comment by Babwenbiber** [comment]
I am not quite sure how to apply that.
In my project, I don't have a pom or build.gradle.
So I have to fork xtext from 2.15 and apply this change into the repo, and then install the customized version?

**Comment by cdietrich** [comment]
No you change the failing exec plugin call

**Comment by Babwenbiber** [comment]
Error comes from executing mwe2.
```
1    [main] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - org/eclipse/core/runtime/OperationCanceledException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/OperationCanceledException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:73)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)

```

**Comment by cdietrich** [comment]
How does your exec configuration look like

**Comment by Babwenbiber** [comment]
GenerateDsl.mwe2:
```

module de.tu_bs.cs.isf.cbc.textual.tool.GenerateDsl

import org.eclipse.xtext.xtext.generator.*
import org.eclipse.xtext.xtext.generator.model.project.*

var rootPath = ".."

Workflow {
	
	component = XtextGenerator {
		configuration = {
			project = StandardProjectConfig {
				baseName = "de.tu_bs.cs.isf.cbc.textual.tool"
				rootPath = rootPath
				eclipsePlugin = {
					enabled = true
				}
				createEclipseMetaData = true
			}
			code = {
				encoding = "UTF-8"
				fileHeader = "/*\n * generated by Xtext \${version}\n */"
			}
		}
		language = StandardLanguage {
			name = "de.tu_bs.cs.isf.cbc.textual.tool.Dsl"
			fileExtensions = "cbctxt"
			referencedResource = "platform:/resource/de.tu-bs.cs.isf.cbc.model/model/cbcmodel.genmodel"
			referencedResource = "platform:/resource/jbase/model/custom/Jbase.genmodel"
			xbaseSupport = jbase.mwe2.generator.JbaseGeneratorFragment2 {}
			
			fragment = ecore2xtext.Ecore2XtextValueConverterServiceFragment2 auto-inject {}

			fragment = org.eclipse.xtext.generator.adapter.FragmentAdapter {
				fragment = org.eclipse.xtext.generator.ecore2xtext.FormatterFragment {}
			}

			serializer = {
				generateStub = false
			}
			validator = {
				// composedCheck = "org.eclipse.xtext.validation.NamesAreUniqueValidator"
			}
		}
	}
}


```

**Comment by cdietrich** [comment]
In the Pom not mwe

**Comment by Babwenbiber** [comment]
Like I said, there is no Pom in my project

**Comment by cdietrich** [comment]
How do you run the workflow

**Comment by cdietrich** [comment]
And which target platform do you use

**Comment by Babwenbiber** [comment]
Here is my MANIFEST.MF
maybe this is what you are looking for.

```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: de.tu_bs.cs.isf.cbc.textual.tool
Bundle-Vendor: My Company
Bundle-Version: 1.0.0.qualifier
Bundle-SymbolicName: de.tu_bs.cs.isf.cbc.textual.tool; singleton:=true
Bundle-ActivationPolicy: lazy
Require-Bundle: de.tu-bs.cs.isf.cbc.model,
 org.eclipse.xtext,
 org.eclipse.equinox.common;bundle-version="3.5.0",
 org.eclipse.xtext.xbase.lib;bundle-version="2.12.0",
 org.eclipse.xtext.util,
 org.eclipse.xtext.xbase,
 jbase,
 jbase.mwe2,
 org.eclipse.xtend.lib;bundle-version="2.15.0",
 org.antlr.runtime;bundle-version="[3.2.0,3.2.1)",
 org.eclipse.xtext.common.types,
 org.objectweb.asm;bundle-version="[5.0.1,6.0.0)";resolution:=optional,
 de.tu-bs.cs.isf.cbc.util;bundle-version="1.0.0",
 org.eclipse.core.resources;bundle-version="3.11.1",
 de.tu-bs.cs.isf.taxonomy.model;bundle-version="0.1.0"
Bundle-RequiredExecutionEnvironment: JavaSE-1.8
Export-Package: de.tu_bs.cs.isf.cbc.textual.tool.generator,
 de.tu_bs.cs.isf.cbc.textual.tool.services,
 de.tu_bs.cs.isf.cbc.textual.tool.scoping,
 de.tu_bs.cs.isf.cbc.textual.tool,
 de.tu_bs.cs.isf.cbc.textual.tool.validation,
 de.tu_bs.cs.isf.cbc.textual.tool.serializer,
 de.tu_bs.cs.isf.cbc.textual.tool.formatting,
 de.tu_bs.cs.isf.cbc.textual.tool.parser.antlr,
 de.tu_bs.cs.isf.cbc.textual.tool.parser.antlr.internal,
 de.tu_bs.cs.isf.cbc.textual.tool.jvmmodel
Import-Package: de.tu_bs.cs.isf.toolkit.support.compare,
 org.apache.log4j
```

I'm building with Jdk and jre 1.8

**Comment by cdietrich** [comment]
No which eclipse version do you use to develop

**Comment by Babwenbiber** [comment]
latest Version: 2021-06 (4.20.0)
Build id: 20210612-2011

**Comment by cdietrich** [comment]
You either have to use 2020-06 or set a target platform 
If you select maven in the new Xtext project wizard you get a .target file. If you open this with the target platform editor there will be a button to use it as target platform

**Comment by Babwenbiber** [comment]
Switching to 2020-06 indeed got rid of the errors described above.
But somehow, Xtend-gen sources do not get generated anymore.

<details>
 <summary>Plugins</summary>

```

  Buildship: Eclipse Plug-ins for Gradle	3.1.4.v20200326-1743	org.eclipse.buildship.feature.group	Eclipse Buildship
  EclEmma Java Code Coverage	3.1.3.202003132300	org.eclipse.eclemma.feature.feature.group	Eclipse EclEmma
  Eclipse IDE for Java Developers	4.16.0.20200615-1200	epp.package.java	Eclipse Packaging Project
  Eclipse Java Development Tools	3.18.400.v20200604-0540	org.eclipse.jdt.feature.group	Eclipse.org
  EMF Code Generation	2.15.0.v20181120-2156	org.eclipse.emf.codegen.feature.group	Eclipse Modeling Project
  EMF Common	2.15.0.v20181220-0846	org.eclipse.emf.common.feature.group	Eclipse Modeling Project
  Git integration for Eclipse	5.8.0.202006091008-r	org.eclipse.egit.feature.group	Eclipse EGit
  JaMoPP - Java Model Parser and Printer	1.4.0.v201207310007	org.emftext.language.java.feature.group	Software Technology Group - TU Dresden
  JaMoPP - Java Model Parser and Printer (Eclipse JDT Integration)	1.4.0.v201207310007	org.emftext.language.java.jdt.feature.group	Software Technology Group - TU Dresden
  Java implementation of Git	5.8.0.202006091008-r	org.eclipse.jgit.feature.group	Eclipse JGit
  Jbase Library Feature	0.9.0.v20180924-1728	jbase.lib.feature.feature.group	Lorenzo Bettini
  Jbase SDK Feature	0.9.0.v20180924-1728	jbase.sdk.feature.group	null
  Jbase UI Feature	0.9.0.v20180924-1728	jbase.ui.feature.feature.group	null
  JML Editing Feature	1.0.0.201710111524	org.key_project.jmlediting.feature.feature.group	KeY Project
  KeY 4 Eclipse Feature	1.0.0.201710111524	org.key_project.key4eclipse.feature.feature.group	KeY Project
  KeY 4 Eclipse Starter Feature	1.0.0.201710111524	org.key_project.key4eclipse.starter.feature.feature.group	KeY Project
  KeY Resources Feature	1.0.0.201710111524	org.key_project.key4eclipse.resources.feature.feature.group	KeY Project
  KeYIDE Feature	1.0.0.201710111524	org.key_project.keyide.feature.feature.group	KeY Project
  m2e - Maven Integration for Eclipse (includes Incubating components)	1.16.0.20200610-1735	org.eclipse.m2e.feature.feature.group	Eclipse.org - m2e
  m2e - slf4j over logback logging (Optional)	1.16.0.20200318-1040	org.eclipse.m2e.logback.feature.feature.group	Eclipse.org - m2e
  Marketplace Client	1.8.3.v20200526-1554	org.eclipse.epp.mpc.feature.group	Eclipse Marketplace Client
  MonKeY Feature	1.0.0.201710111524	org.key_project.monkey.feature.feature.group	KeY Project
  MWE 2 language SDK	2.9.0.v201605261103	org.eclipse.emf.mwe2.language.sdk.feature.group	Eclipse Xtext
  Mylyn WikiText	3.0.36.202002070035	org.eclipse.mylyn.wikitext_feature.feature.group	Eclipse Mylyn
  OCL Classic: Ecore Parser,Evaluator	3.6.0.v20160523-1914	org.eclipse.ocl.feature.group	Eclipse Modeling Project
  POM Editor using LemMinX language server (includes Incubating components)	1.16.0.20200609-1359	org.eclipse.m2e.lemminx.feature.feature.group	Eclipse.org - m2e
  Remove Generics Feature	1.0.0.201710111524	org.key_project.removegenerics.feature.feature.group	KeY Project
  Shell Utility Feature	1.0.0.201710111524	org.key_project.shellutility.feature.feature.group	KeY Project
  Sirius Properties Views - Runtime Support	6.5.1.202106111115	org.eclipse.sirius.properties.feature.feature.group	Eclipse Modeling Project
  Sirius Specifier Environment	6.5.1.202106111115	org.eclipse.sirius.specifier.feature.group	Eclipse Modeling Project
  Sirius Support for AQL	6.5.1.202106111115	org.eclipse.sirius.aql.feature.group	Eclipse Modeling Project
  Tip of the Day UI Feature	0.2.1000.v20200522-1444	org.eclipse.tips.feature.feature.group	Eclipse.org
  Wild Web Developer XML tools	0.10.0.202006021616	org.eclipse.wildwebdeveloper.xml.feature.feature.group	Eclipse Wild Web Developer project
  Xtend IDE	2.15.0.v20180916-1232	org.eclipse.xtend.sdk.feature.group	Eclipse Xtend
  Xtext Complete SDK	2.15.0.v20180916-1232	org.eclipse.xtext.sdk.feature.group	Eclipse Xtext
```

</details>

**Comment by cdietrich** [comment]
is there anything in the error log? did you do a clean build? do you have build automatically on?

**Comment by Babwenbiber** [comment]
nothing xtext related in the error log.
I cleaned the project and have automatically build on.
I even tried to start with a fresh ws.

**Comment by cdietrich** [comment]
but xtend files are recognized or does xtend not start at all.
check the osgi console

ss xtend
then
start <numberof xtend.ide>

**Comment by Babwenbiber** [comment]
Indeed some issues:

<img width="1440" alt="Bildschirmfoto 2021-06-29 um 09 46 12" src="https://user-images.githubusercontent.com/15171332/123758241-05a53b80-d8bf-11eb-85d6-1a8b799cc78d.png">
<img width="1440" alt="Bildschirmfoto 2021-06-29 um 09 46 22" src="https://user-images.githubusercontent.com/15171332/123758260-0938c280-d8bf-11eb-87de-5ef080a86a3b.png">

**Comment by cdietrich** [comment]
this looks like a incomlete install. which distro did you use?

**Comment by Babwenbiber** [comment]
update site: http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/
installed: emf common, emf code generation, Xtend IDE, Xtext Complete SDK (all 2.15) MWE2 Language SDK 2.9

**Comment by cdietrich** [comment]
maybe you can try https://www.eclipse.org/downloads/packages/release/2020-06/r/eclipse-ide-java-and-dsl-developers

**Comment by cdietrich** [comment]
(or the older version that has xtext 2.15 
https://www.eclipse.org/downloads/packages/release/2018-09/r/eclipse-ide-java-and-dsl-developers

**Comment by Babwenbiber** [comment]
Using the 2018 version worked for me, thanks.
