### ISSUE TITLE
Investigate failing reference projects

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2043]
```
Run MWE2 for [org.eclipse.xtext.example.fowlerdsl, src, org.eclipse.xtext.example.fowlerdsl, GenerateStatemachine.mwe2]

!ENTRY org.eclipse.core.jobs 4 2 2022-02-26 06:11:06.559
!MESSAGE An internal error occurred during: "Launching GenerateStatemachine.mwe2".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.jdt.launching.AbstractJavaLaunchConfigurationDelegate.getBootpathExt(AbstractJavaLaunchConfigurationDelegate.java:364)
	at org.eclipse.jdt.launching.AbstractJavaLaunchConfigurationDelegate.getVMSpecificAttributesMap(AbstractJavaLaunchConfigurationDelegate.java:679)
	at org.eclipse.jdt.launching.JavaLaunchDelegate.getVMRunnerConfiguration(JavaLaunchDelegate.java:92)
	at org.eclipse.jdt.launching.JavaLaunchDelegate.launch(JavaLaunchDelegate.java:160)
	at org.eclipse.emf.mwe2.launch.shortcut.Mwe2LaunchDelegate.launch(Mwe2LaunchDelegate.java:54)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:803)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1021)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1224)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by cdietrich** [comment]
the wizard tests also struggle with sonatype
unclear
- problem on sonatype side?
- change in m2e
- maven update missing / changed whatever
- shared maven repo not used?!?

```
2022-02-27T06:05:30.4502913Z [INFO] ------------------------------------------------------------------------
2022-02-27T06:05:30.4503147Z [INFO] BUILD SUCCESS
2022-02-27T06:05:30.4503577Z [INFO] ------------------------------------------------------------------------
2022-02-27T06:05:30.4503818Z [INFO] Total time:  02:35 min
2022-02-27T06:05:30.4504092Z [INFO] Finished at: 2022-02-27T06:05:30Z
2022-02-27T06:05:30.4504445Z [INFO] ------------------------------------------------------------------------
2022-02-27T06:05:30.4504606Z 
2022-02-27T06:05:30.4506258Z Success after: 157sec
2022-02-27T06:05:30.4556928Z Refresh all projects
2022-02-27T06:05:30.4667707Z Collapse all projects
2022-02-27T06:05:32.1812814Z Execute 'Eclipse Build'
2022-02-27T06:05:35.0802051Z Execute 'Eclipse Build'
2022-02-27T06:05:35.0891716Z Execute 'Clean Build'
2022-02-27T06:05:35.2412726Z Execute 'Eclipse Build'
2022-02-27T06:05:39.3414193Z Get error messages: [Could not read maven project
2022-02-27T06:05:39.3414639Z , Could not read maven project
2022-02-27T06:05:39.3414924Z , Could not read maven project
2022-02-27T06:05:39.3415447Z , Could not read maven project
2022-02-27T06:05:39.3415774Z , Could not read maven project
2022-02-27T06:05:39.3416028Z , Could not read maven project
2022-02-27T06:05:39.3416297Z , Could not read maven project
2022-02-27T06:05:39.3416543Z , Could not read maven project
2022-02-27T06:05:39.3416809Z , Could not read maven project
2022-02-27T06:05:39.3418248Z , org.eclipse.xtext:xtext-dev-bom:pom:2.26.0-SNAPSHOT failed to transfer from https://oss.sonatype.org/content/repositories/snapshots during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced. Original error: Could not transfer artifact org.eclipse.xtext:xtext-dev-bom:pom:2.26.0-SNAPSHOT from/to sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots): The operation was cancelled.
```

**Comment by cdietrich** [comment]
log has also 
```
Reset and clear all consoles
 - no button found 'Remove All Terminated Launches'
```

**Comment by cdietrich** [comment]
adding a maven refresh solved the problem

**Comment by cdietrich** [comment]
sill some instabilities, but no more constant fails

**Comment by cdietrich** [comment]
[[code][/code]](https://github.com/itemis/xtext-reference-projects/issues/246)
an a workaround/mitigation i 

    sparated builds into multiple workflows
    replicated build on ci.eclipse.org
