### ISSUE TITLE
org.eclipse.xtext.xbase.ui.hover.XbaseInformationControl: Not properly disposed SWT resource

### ISSUE THREAD

**Issue by jukzi** [eclipse/xtext#2050]
found in logfile:

java.lang.Error: SWT Resource was not properly disposed
	at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
	at org.eclipse.swt.graphics.TextLayout.<init>(TextLayout.java:176)
	at org.eclipse.xtext.xbase.ui.hover.XbaseInformationControl.createTextLayout(XbaseInformationControl.java:572)
	at org.eclipse.xtext.xbase.ui.hover.XbaseInformationControl.createContent(XbaseInformationControl.java:176)
	at org.eclipse.jface.text.AbstractInformationControl.create(AbstractInformationControl.java:437)
	at org.eclipse.xtext.xbase.ui.hover.XbaseInformationControl.<init>(XbaseInformationControl.java:96)
	at org.eclipse.xtext.xbase.ui.hover.XbaseHoverProvider$XbaseHoverControlCreator$1.<init>(XbaseHoverProvider.java:389)
	at org.eclipse.xtext.xbase.ui.hover.XbaseHoverProvider$XbaseHoverControlCreator.doCreateInformationControl(XbaseHoverProvider.java:389)
	at org.eclipse.jface.text.AbstractReusableInformationControlCreator.createInformationControl(AbstractReusableInformationControlCreator.java:46)
	at org.eclipse.jface.text.AbstractInformationControlManager.getInformationControl(AbstractInformationControlManager.java:829)
	at org.eclipse.jface.text.AbstractInformationControlManager.internalShowInformationControl(AbstractInformationControlManager.java:1138)
	at org.eclipse.jface.text.AbstractInformationControlManager.presentInformation(AbstractInformationControlManager.java:1120)
	at org.eclipse.jface.text.AbstractHoverInformationControlManager.presentInformation(AbstractHoverInformationControlManager.java:884)
	at org.eclipse.jface.text.TextViewerHoverManager.doPresentInformation(TextViewerHoverManager.java:237)
	at org.eclipse.jface.text.TextViewerHoverManager.lambda$3(TextViewerHoverManager.java:227)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4035)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3635)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

**Comment by miklossy** [comment]
Thanks for the bug report @jukzi ! I have also observed this problem in a customer project.

**Comment by cdietrich** [comment]
which xtext version do you use @miklossy @jukzi . see https://github.com/eclipse/xtext-eclipse/issues/1699

**Comment by jukzi** [comment]
i used a 3 week old master branch

**Comment by miklossy** [comment]
I use Xtext 2.25

**Comment by cdietrich** [comment]
@jukzi i tested it with 2.26 release and could not reproduce.
https://github.com/eclipse/xtext-eclipse/pull/1700/files
should have fixed it.

@miklossy can you reproduce it with 2.26?

**Comment by cdietrich** [comment]
i see dispose called as expected
<img width="1320" alt="Bildschirmfoto 2022-03-24 um 12 47 26" src="https://user-images.githubusercontent.com/238736/159910008-8020dbe7-3e99-4bc4-9770-1eae41d65beb.png">

**Comment by cdietrich** [comment]
@jukzi your stacktrace
https://github.com/eclipse/xtext-eclipse/blob/f368d3d214fd1165aa09f4d838d667a1cdd090a0/org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseInformationControl.java#L572
https://github.com/eclipse/xtext-eclipse/blob/18904b97d211687485a881a633c2a68c5a3b1b57/org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseInformationControl.java#L572

indicates that you are still using 2.25.0 and not a 3 week old snapshot in the eclipse you do the hovering
(e.g. dev eclipse vs target platform)

**Comment by jukzi** [comment]
oh, true. i had 2.25.0.v20210301-0928 in the IDE and master in the target platform IDE .... confusing

**Comment by cdietrich** [comment]
dupes https://github.com/eclipse/xtext-eclipse/issues/1699

**Comment by miklossy** [comment]
Thanks for clarifying it @cdietrich ! I will update to Xtext 2.26 soon and hopefully the problem wii be fixed.
