### ISSUE TITLE
Guice upgrade to 7.0.0+

### ISSUE THREAD

**Issue by frankbenoit** [eclipse/xtext#2056]
At is listed in Guice 5.1.0, they fixed issues to support Java 17.
https://github.com/google/guice/wiki/Guice510

First step would be to bring it onto Eclipse Orbit.
If there is not yet such an activity already, I can do that receipt again.
@cdietrich a CQ is needed, i guess.

**Comment by cdietrich** [comment]
hi, i dont know about cq. in doubt you can ask on the emo mailing list
but i have doubts i can work on this at all.
cause i have to deal with all the orbit cvs fallout until end of M3

**Comment by HannesWell** [comment]
With the upcoming release Eclipse-platform fully supports to obtain dependencies directly from Maven-Central:
https://www.eclipse.org/lists/cross-project-issues-dev/msg19066.html

If the Guice jars contain a OSGi compliant MANIFEST.MF Orbit can be skipped.

**Comment by cdietrich** [comment]
@HannesWell no it cant, cause there is no solution for oomph and tycho 1.7

**Comment by HannesWell** [comment]
> @HannesWell no it cant, cause there is no solution for oomph and tycho 1.7 

What Eclipse-Platform is doing is to include the I-Build repo (which includes all dependencies) in their Oomph setup, which contains those dependencies.
Effectively a p2-repo is build by Maven/Tycho that includes the Maven-Central dependencies and the Oomph setup then fetches those dependencies from that repo.
Although this is a bit cumbersome (it requires a successful nightly build to make the Oomph setup work) it is at least an already working solution. It would be simpler if it were possible to reference a target-file in an Oomph targlet.

Aren't you planning to update to [Tycho 2.7.2](https://github.com/eclipse/xtext/issues/2060)?

> nor have i any idea what needs to be setup for signing

That's the good thing: Nothing. The PGP-signature should be understood by P2 just like jar-signatures.

Another point is that XText should make sure licences are vetted correctly. But also for this task GitHub workflows for Maven exist that can be copied:
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/.github/workflows/licensecheck.yml
But IIRC this also requires a recent Tycho version.

**Comment by cdietrich** [comment]
we dont want to use our old builds in oomph. oomph also has to work with older target platform, so we cannot use platform i-builds there.

**Comment by cdietrich** [comment]
we support platform back to oxygen and java 8,11 and 17 (partially)
i mean instead of using bnd to package stuff to orbit to use the thing that platform uses at orbit.
then everybody can use orbit as used and has not to fight with the new tycho features

**Comment by HannesWell** [comment]
> we support platform back to oxygen and java 8,11 and 17 (partially)

That's a long history. Then I suspect you need jarsigned dependencies. Unless it is acceptable that consumers get warnings about unsigned content when installing xtext (respectively Guice) into older platforms.

> i mean instead of using bnd to package stuff to orbit to use the thing that platform uses at orbit.

I never contributes to orbit so don't know the exact details how Orbit works but AFAICT it basically re-creates the jars from (for example) Maven-Central using the original class files but adds a custom Manifest (if necessary) with partially Eclipse-custom metadata and performs own jar-signing. On the other hand when using Tycho to mirror Maven artifacts into a P2 repo (like you did in https://github.com/xtext/xtext-orbit-replacement) it just copies to jar into a new folder structure and creates a corresponding artifact/content.xml metadata, if that artifact has a OSGi compliant MANIFEST. If not Tycho (like M2E) uses BND-tools to generate one suitable MANIFEST. So in the end that process is likely not that different to what Orbit is/was doing already.

Maybe Orbit is already leveraging Tycho in this way, as I have not yet looked into the details of the Orbit process.
 
> then everybody can use orbit as used and has not to fight with the new tycho features
> so instead of having 20 project with no people to do the same fight on their own
> to do it once at orbit

Yes that is not ideal.

> and i have zeroclue about jar vs pgp signing and what is verified where and how

I'm not an expert either. Basically these are two different techniques to very the integrity and creator of a jar. The former is can be used with tools build into the JDK the latter one is mandatory to publish artifacts to Maven-Central (I suspect they choose that technique because you don't need a jarsigning certificate from a Certification-authority which usually costs some money).

Btw. if you want to proceed with https://github.com/xtext/xtext-orbit-replacement you maybe want to add the `eclipse-jarsigner-plugin` to ensure all jars in the repo are jarsigned. In M2E we do that as well:
https://github.com/eclipse-m2e/m2e-core/blob/342a148d91473a2bb7f4c186635936ccb277eb61/org.eclipse.m2e.repository/pom.xml#L42

However as you said this should not be done by each project individually. So I suggest to ask Orbit to include the new Guice.
@frankbenoit do you want to continue to create a receipt?

**Comment by cdietrich** [comment]
the current orbit manifest has [30.1,31)
but we might also update to guava 31 https://github.com/eclipse/xtext/issues/2101

**Comment by cdietrich** [comment]
@merks do you still have the report where one can see what depends on what so that we can see who else not related to xtext uses guice?

**Comment by merks** [comment]
These are all users with requirements that are satisfied by only one available version:

![image](https://user-images.githubusercontent.com/208716/191435419-3940d0b2-5f8e-447a-944d-5940b0002049.png)

Most would be satisfied also with a version < 6.0.

Note that if you install a SimRel IDE using the Oomph link here:

https://ci.eclipse.org/simrel/

You can open the simrel.aggran and view this information for the current state the SimRel contributions.

**Comment by cdietrich** [comment]
the oom issue got merged in guice
https://github.com/google/guice/issues/1510
lets see when this is published

**Comment by HannesWell** [comment]
A new guice release is planned soon (probably guice 6.0), which will also support jakarta.inject (almost completely):
https://github.com/google/guice/issues/1383#issuecomment-1523410855

**Comment by cdietrich** [comment]
https://github.com/google/error-prone/issues/2967

**Comment by cdietrich** [comment]
somehow does not work in 202203

```
14:11:27  [INFO] {osgi.os=macosx, osgi.ws=cocoa, org.eclipse.update.install.features=true, osgi.arch=x86_64}
14:11:27  [ERROR] Cannot resolve project dependencies:
14:11:27  [ERROR]   Software being installed: org.eclipse.xtext.xbase.lib 2.31.0.qualifier
14:11:27  [ERROR]   Missing requirement: com.google.guava 31.1.0.jre requires 'java.package; com.google.common.util.concurrent.internal [1.0.0,2.0.0)' but it could not be found
14:11:27  [ERROR]   Cannot satisfy dependency: org.eclipse.xtext.xbase.lib 2.31.0.qualifier depends on: osgi.bundle; com.google.guava [31.1.0,32.0.0)
14:11:27  [ERROR] 
```

**Comment by cdietrich** [comment]
junit5 tests also make problems https://ci.eclipse.org/xtext/job/xtext/job/cd_guice6x/3/testReport/junit/org.eclipse.xtext.testing.tests.junit5/InjectionExtensionNested2Test$NestedClass/innerTest/

**Comment by merks** [comment]
I spent a lot of time trying to get this to work.  You may wish to read the saga here:

https://github.com/merks/simrel-maven/issues/4

**Comment by cdietrich** [comment]
@LorenzoBettini do you know if there is a way to exclude specific p2 deps from the maven surefire run?

**Comment by cdietrich** [comment]
also mwe has strict dependency to older guava

**Comment by LorenzoBettini** [comment]
Maybe this one https://tycho.eclipseprojects.io/doc/latest/target-platform-configuration/target-platform-configuration-mojo.html#filters but I've never used that.

What about forcing in the POM the dependency containing `com.google.common.util.concurrent.internal`?

**Comment by HannesWell** [comment]
> the error_prone dependency does not seem to have proper manifest. in orbit we exclude it so far i know
> 
> @HannesWell is there an option to exclude certain transitives with the maven deps in target feature?

Yes, when you have transitive dependencies (either only direct or infinite) included you can exclude them in the location definition Editor, as described here: https://github.com/eclipse-m2e/m2e-core/issues/286#issuecomment-1356431301
This issue also has the goal to support more maven like exclusion syntax, I put it on my TODO-list.

Alternatively you could simply not include any dependencies (Edit -> Dependency Depth: `None`) and just list the artifacts you want to include.

> I spent a lot of time trying to get this to work. You may wish to read the saga here:
> 
> [merks/simrel-maven#4](https://github.com/merks/simrel-maven/issues/4)

Sorry Ed, for the silence, I'll try to have a look at it this tonight.

**Comment by merks** [comment]
This exists now:

https://repo1.maven.org/maven2/com/google/inject/guice/6.0.0-rc1/

But it still has the error prone, error prone dependency.

**Comment by cdietrich** [comment]
@merks yes and it uses outdated guava (31.0.1 instead of 31.1)

**Comment by cdietrich** [comment]
next testfail i dont understand

java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.core.IType.getFullyQualifiedName()" because the return value of "org.eclipse.jdt.core.IType.getDeclaringType()" is null
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.createHandle(MatchLocator.java:528)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2545)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3298)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3310)
	at org.eclipse.jdt.internal.core.search.matching.MemberDeclarationVisitor.visit(MemberDeclarationVisitor.java:330)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1714)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.traverse(QualifiedAllocationExpression.java:693)
	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.traverse(ReturnStatement.java:390)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:411)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2586)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3298)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2862)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2037)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1310)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1390)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1532)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:251)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:602)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
	at org.eclipse.xtext.common.types.xtext.ui.JdtBasedConstructorScope.collectContents(JdtBasedConstructorScope.java:100)
	at org.eclipse.xtext.common.types.xtext.ui.JdtBasedConstructorScope.internalGetAllElements(JdtBasedConstructorScope.java:75)
	at org.eclipse.xtext.common.types.xtext.AbstractConstructorScope.getAllElements(AbstractConstructorScope.java:104)
	at org.eclipse.xtext.common.types.access.xtext.ui.JdtBasedConstructorScopeTest.testGetContents_01(JdtBasedConstructorScopeTest.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:74)
	at org.eclipse.pde.internal.junit.runtime.PlatformUITestHarness.lambda$0(PlatformUITestHarness.java:45)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4320)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3943)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.runApp(NonUIThreadTestApplication.java:53)
	at org.eclipse.pde.internal.junit.runtime.UITestApplication.runApp(UITestApplication.java:47)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.start(NonUIThreadTestApplication.java:48)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

assume there is something broken with the test project setup

**Comment by cdietrich** [comment]
type in question is MapEntry (not open) [in HashBiMap$1$MapEntry.class [in com.google.common.collect [in /Users/cdietrich/.m2/repository/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar]]]

@trancexpress @iloveeclipse does the stacktrace above ring a bell to you?

**Comment by iloveeclipse** [comment]
Please report jdt bug. I assume the type defined in anonymous type runs search into trouble. Is this with the 4.28 platform or with older one? We're fixed few search use cases in 4.28.

**Comment by cdietrich** [comment]
@iloveeclipse will check if this is fixed in 4.28

**Comment by iloveeclipse** [comment]
Actually that should be fixed in 4.25 M3 via https://github.com/eclipse-jdt/eclipse.jdt.core/issues/247

**Comment by cdietrich** [comment]
tests on 4.25 look good as well

**Comment by HannesWell** [comment]
Guice 6 (supporting javax- and most of the jakarta-annotations) respectively 7 (supporting only but all jakarta-annotations) is around the corner:
https://github.com/google/guice/discussions/1732#discussioncomment-5867621

Is there also a plan regarding guice 7? As far as I understand, as long as one does not use javax-annotations using guice 7 should be straight forward.
@cdietrich I also saw in your branch that you only specified a lower bound for the com.google.inject bundle in the MANIFEST.MF files. Was this intentional to support all later versions too? In case you want to change to a closed source one day I recommend to use `[6.0,8)` so that a user can decide what to choose for the application.

**Comment by cdietrich** [comment]
There is no concrete plan yet. I am just experimenting

**Comment by HannesWell** [comment]
> There is no concrete plan yet. I am just experimenting (with both 6 and 7, see corr. branches)

Do you think Guice 6/7 will make it into the up-coming summer release? Especially the resulting compatibility with guava 31 would be highly appreciated, because in the previous release conflicting guava versions in the SimRel were a problem.

**Comment by cdietrich** [comment]
i dont have the confidence to get this done in the remaining 6 days

**Comment by HannesWell** [comment]
> i dont have the confidence to get this done in the remaining 6 days for both xtext and mwe. i am also on vacation this week and the test branches have some shortcuts

Understand. Would you then accept a PR to make Xtext compatible with Guava 31, i.e. only widen the required-bundle/import-package version range to also include guava 31 and add guava 31 to the latest TP? Although the currently used Guice 5.0.1 requires guava 30, this will allow to at least be able run Xtext with Guava 31 (although this means one needs two versions of guava in an application).

Because `org.eclipse.xtext.util` and `org.eclipse.xtext.xbase.lib` reexport guava it really gets messy if there is guava 30.1.0 (from Eclipse Orbit) and Guava 31.1 (from Maven-Centra) in one OSGi runtime.

**Comment by cdietrich** [comment]
I don’t know how to test. In the past version ranges were a bad idea
We also would have to do it for mwe
Build a mwe milestone 
Use mwe milestone 
Build mwe release
Use mwe release
And I have no time 

I also don’t know how this should work with guice as we also use guice and guava together everywhere. So a pure guava update won’t work, will it ?!?

i also already have to do the lsp4j update later this week

and others (Sebastian/Lorenzo) seem to be busy too

**Comment by HannesWell** [comment]
I just created a PR that only widens the version range to include Guava 31:
- https://github.com/eclipse/xtext/pull/2671

Lets see if that works.
This should also test it with the xtext-latest target and if it works as I hope, a MWE release is not necessary.

**Comment by cdietrich** [comment]
yes and no
had to do this to test
https://github.com/eclipse/mwe/compare/cd_guava_loosen_range?expand=1

**Comment by cdietrich** [comment]
still see a ton of issues. also check comments in https://github.com/eclipse/xtext/pull/2671

**Comment by cdietrich** [comment]
did some experiments with guice 7 + guava 32 at https://github.com/eclipse/xtext/tree/cd_testg32guice7

now i try to get it to simrel maven https://github.com/eclipse-oomph/oomph.incubator/pull/1/files

**Comment by HannesWell** [comment]
> now i try to get it to simrel maven https://github.com/eclipse-oomph/oomph.incubator/pull/1/files

Just want to mention that with https://github.com/eclipse/xtext/pull/2207 you would not have to deal with simrel maven and could just add any new version of guice to xtext's TP.

**Comment by cdietrich** [comment]
i know

**Comment by cdietrich** [comment]
@frankbenoit in case you also need assisted inject. can you get in contact with  @merks  to get it into simrel maven p2 repo

**Comment by cdietrich** [comment]
in the old orbit there was also 

```
    <dependency>
      <groupId>com.google.inject.extensions</groupId>
      <artifactId>guice-assistedinject</artifactId>
      <version>5.0.1</version>
    </dependency>
```
which was not used by Xtext diretly but by Xtext consumers (@frankbenoit )

**Comment by merks** [comment]
There's a 5.1.0 version but it fails during my build because it needs a very restricted version of com.google.common.base 

> [ERROR]   Missing requirement: com.google.inject.assistedinject 5.1.0 requires 'java.package; com.google.common.base [30.1.0,31.0.0)' but it could not be found
> [ERROR]   Cannot satisfy dependency: org.eclipse.oomph.maven.all.feature.group 4.29.0 depends on: org.eclipse.equinox.p2.iu; com.google.inject.assistedinject [5.1.0,5.1.0]

There are also 6.x and 7.x versions, but they fail the build like this:

> [ERROR]   Missing requirement: com.google.inject.assistedinject 7.0.0 requires 'java.package; com.google.errorprone.annotations 0.0.0' but it could not be found
> [ERROR]   Cannot satisfy dependency: org.eclipse.oomph.maven.all.feature.group 4.29.0 depends on: org.eclipse.equinox.p2.iu; com.google.inject.assistedinject [7.0.0,7.0.0]


With both of these, resolution works:

>         <dependency>
>           <groupId>com.google.inject.extensions</groupId>
>           <artifactId>guice-assistedinject</artifactId>
>           <version>7.0.0</version>
>         </dependency>
> 
>         <dependency>
>           <groupId>com.google.errorprone</groupId>
>           <artifactId>error_prone_annotations</artifactId>
>           <version>2.20.0</version>
>         </dependency>

So I guess that's what folks want?

**Comment by cdietrich** [comment]
what did you do for normal guava/guice not to need errorprone

**Comment by merks** [comment]
I did nothing.  All the dependencies come directly from Maven with the OSGi metadata as specified in the maven-hosted jar:

https://github.com/eclipse-oomph/oomph.incubator/blob/master/maven/tp/Maven.target

I think other places removed the package imports themselves or maybe with some gentle help from @HannesWell 

You can follow the links from the report:

https://github.com/eclipse-oomph/oomph.incubator/blob/master/maven/org.eclipse.oomph.maven.generator/report/merged-target/REPORT.md

**Comment by HannesWell** [comment]
> I think other places removed the package imports themselves or maybe with some gentle help from @HannesWell

Yes, I made the error-prone dependency optional in guice via https://github.com/google/guice/pull/1739, which is included in guice 6 and 7.

For the extensions that still require the annotations, I also contributed proper metadata to error-prone itself via https://github.com/google/error-prone/pull/3903, which is included in the recent [error-prone 2.20.0](https://github.com/google/error-prone/releases/tag/v2.20.0) release. I assume one can use that as a drop-in replacement for 2.19, which quice requires.

> which was not used by Xtext diretly but by Xtext consumers (@frankbenoit )

Can't down-stream consumers add the extension via Maven-Targets by themself?
Then Xtext/(Maven-)SimRel/Orbit would not have to take care about that. :)

**Comment by laeubi** [comment]
> Yes, I made the error-prone dependency optional in guice via https://github.com/google/guice/pull/1739, which is included in guice 6 and 7.

Making it optional might have not the desired effect one do think, it should instead be scope `provided` or something like that....

**Comment by laeubi** [comment]
> is there such a thing in P2?

P2 has nothing to do with maven, and as said "optional" in maven means something completely different than one might think:
https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

> Optional dependencies save space and memory. They prevent problematic jars that violate a license agreement or cause classpath issues from being bundled into a WAR, EAR, fat jar, or the like. 

this does not makes the dependency "optional" in the sense of that one don't need it to build the project, I think there is more a problem with einter BND, outdated BND or manual crafted manifests, as BND should already detect class only annotations and not include them in the manifest.

**Comment by cdietrich** [comment]
Fixed in 2.32

**Comment by frankbenoit** [comment]
Guice 7 does no more support javax.inject. 
This breaks peaberry, which does not know anything about jakarta.
In Eclipse in combination with Xtext and Guice, peaberry might be used often. At least in my projects :-)
Is there a known solution?

**Comment by cdietrich** [comment]
i assume they can install old guices from old orbits
