### ISSUE TITLE
A transient dependency issue is affecting compilation of xtext projects

### ISSUE THREAD

**Issue by denisoliveirac** [eclipse/xtext#2077]
Hi.

My xtext project stopped compiling today. Apparently a transient dependency has been deleted or modified. See the error below:

```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':myproject:generateXtext'.
> Could not resolve all files for configuration ':myproject:xtendToolingMain'.
   > Could not find any matches for org.osgi.service:org.osgi.service.prefs:[1.1.0,1.2.0) as no versions of org.osgi.service:org.osgi.service.prefs are available.
     Searched in the following locations:
       - file:/home/user/.m2/repository/org/osgi/service/org.osgi.service.prefs/
       - https://repo.maven.apache.org/maven2/org/osgi/service/org.osgi.service.prefs/maven-metadata.xml
     Required by:
         project :myproject > org.eclipse.xtend:org.eclipse.xtend.core:2.27.0 > org.eclipse.platform:org.eclipse.core.runtime:3.25.0 > org.eclipse.platform:org.eclipse.equinox.preferences:3.10.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 12s
2 actionable tasks: 2 executed
```

**Comment by SheppN** [comment]
I'm seeing the same thing. It's coming from `org.eclipse.equinox.preferences:3.10.0` which has a dependency for   `org.osgi.service:org.osgi.service.prefs` in its pom, but the group should be just `org.osgi` I think (based on org.osgi.service.prefs pom). I don't see org.eclipse.equinox.preferences:3.10.0 on mvnrepository so not quite sure where we're pulling that in from (well, it's jcenter via Artifactory, but I thought that was sunsetted).

If it helps you, or anyone who stumbles upon this, I was able to get around this for my build by setting a resolutionStrategy like below, though that should just be temporary until this is fixed:
```
configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute module('org.osgi.service:org.osgi.service.prefs') with module('org.osgi:org.osgi.service.prefs:1.1.2')
    }
}
```
That still brings in `org.eclipse.equinox.preferences:3.10`, so something like `force org.eclipse.platform:org.eclipse.equinox.preferences:3.9.100` instead of the `substitute` might be better/achieve the same goal.

**Comment by denisoliveirac** [comment]
The workaround above solve the compilation problem but cause another problem in unit tests.
I use a excluded group `exclude group: 'org.osgi.service'` in configurations and the problem is the same.

I disable my unit tests and froze the changes in language project (xtext project) until the problem is solved.

```

    com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: java.lang.SecurityException: class "org.eclipse.core.runtime.OperationCanceledException"'s signer information does not match signer information of other classes in the same package
        at app//com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
        at app//com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
        at app//com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
        at app//com.google.inject.internal.FailableCache.get(FailableCache.java:50)
        at app//com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
        at app//com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:125)
        at app//com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:521)
        at app//com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:847)
        at app//com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
        at app//com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
        at app//com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
        at app//com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
        at app//com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:46)
        at app//com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:50)
        at app//com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:133)
        at app//com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at app//com.google.inject.Guice.createInjector(Guice.java:95)
        at app//com.google.inject.Guice.createInjector(Guice.java:72)
        at app//com.google.inject.Guice.createInjector(Guice.java:62)
        at app//org.eclipse.xtext.xbase.XtypeStandaloneSetupGenerated.createInjector(XtypeStandaloneSetupGenerated.java:45)
        at app//org.eclipse.xtext.xbase.XtypeStandaloneSetupGenerated.createInjectorAndDoEMFRegistration(XtypeStandaloneSetupGenerated.java:39)
        at app//org.eclipse.xtext.xbase.XtypeStandaloneSetup.createInjectorAndDoEMFRegistration(XtypeStandaloneSetup.java:31)
        at app//org.eclipse.xtext.xbase.XtypeStandaloneSetup.doSetup(XtypeStandaloneSetup.java:24)
        at app//org.eclipse.xtext.xbase.XbaseStandaloneSetupGenerated.createInjectorAndDoEMFRegistration(XbaseStandaloneSetupGenerated.java:23)
        at app//org.eclipse.xtext.xbase.XbaseStandaloneSetup.createInjectorAndDoEMFRegistration(XbaseStandaloneSetup.java:28)
        at app//org.eclipse.xtext.xbase.XbaseStandaloneSetup.doSetup(XbaseStandaloneSetup.java:22)
        at app//kunumi.NumiStandaloneSetupGenerated.createInjectorAndDoEMFRegistration(NumiStandaloneSetupGenerated.java:21)
        at app//kunumi.tests.NumiInjectorProvider.internalCreateInjector(NumiInjectorProvider.java:40)
        at app//kunumi.tests.NumiInjectorProvider.getInjector(NumiInjectorProvider.java:28)
        at app//kunumi.tests.NumiInjectorProvider.setupRegistry(NumiInjectorProvider.java:65)
        at app//org.eclipse.xtext.testing.XtextRunner.methodBlock(XtextRunner.java:44)
        at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at app//org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at app//org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at app//org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base@11.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@11.0.11/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
        at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

        Caused by:
        com.google.inject.internal.util.$ComputationException: java.lang.SecurityException: class "org.eclipse.core.runtime.OperationCanceledException"'s signer information does not match signer information of other classes in the same package
            at app//com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
            at app//com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
            at app//com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
            at app//com.google.inject.internal.FailableCache.get(FailableCache.java:50)
            at app//com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:65)
            at app//com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:73)
            at app//com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:28)
            at app//com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:36)
            at app//com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:32)
            at app//com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
            at app//com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
            ... 61 more

            Caused by:
            java.lang.SecurityException: class "org.eclipse.core.runtime.OperationCanceledException"'s signer information does not match signer information of other classes in the same package
                at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1151)
                at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:906)
                at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1015)
                at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
                at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
                at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
                at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
                at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
                at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
                at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
                at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
                at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2357)
                at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:243)
                at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:96)
                at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:629)
                at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:845)
                at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
                at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
                at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
                at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
                at com.google.inject.internal.SingleFieldInjector.<init>(SingleFieldInjector.java:41)
                at com.google.inject.internal.MembersInjectorStore.getInjectors(MembersInjectorStore.java:125)
                at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:95)
                at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:34)
                at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42)
                at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:39)
                at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
                at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
                ... 71 more

```

**Comment by cdietrich** [comment]
can you please provide a reproducer

**Comment by cdietrich** [comment]
to me this also looks like a bug in eclipse platform and their scripts that create the maven deps
org.osgi.service:org.osgi.service.prefs
should be org.osgi:org.osgi.service.prefs

**Comment by cdietrich** [comment]
my gradle builds work,
but tycho ones fail:

```
 Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (mwe2Launcher) on project org.xtext.example.mydsl: Execution mwe2Launcher of goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java failed: Plugin org.codehaus.mojo:exec-maven-plugin:3.0.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.codehaus.mojo:exec-maven-plugin:jar:3.0.0 -> org.eclipse.xtext:org.eclipse.xtext.xtext.generator:jar:2.28.0-SNAPSHOT -> org.eclipse.emf:org.eclipse.emf.codegen:jar:2.19.0 -> org.eclipse.platform:org.eclipse.core.runtime:jar:3.12.0 -> org.eclipse.platform:org.eclipse.equinox.preferences:jar:3.10.0 -> org.osgi.service:org.osgi.service.prefs:jar:[1.1.0,1.2.0): No versions available for org.osgi.service:org.osgi.service.prefs:jar:[1.1.0,1.2.0) within specified range -> [Help 1]
```

**Comment by cdietrich** [comment]
eclipse platform has pulled the bad artifact(s) from maven central. so (at least after the clearing of local maven repos or mirrors) the problem should be solved

**Comment by stefan-ka** [comment]
Hi @cdietrich 
We run in the same problem these days... Do you know which artifacts have to be cleared from mirrors/caches? Which are those "bad" artifacts?
Thanks and best regards,
Stefan

**Comment by cdietrich** [comment]
See https://github.com/eclipse-platform/eclipse.platform.releng/issues/47
