### ISSUE TITLE
Problem with AA in freshly oomphed eclipse

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2163]
in freshly oomphed eclipse when i open and touch
TargetPlatformProject.xtend
am getting

```
java.lang.IllegalStateException: Problem during instantiation of org.eclipse.xtend.lib.annotations.FinalFieldsConstructorProcessor : org.eclipse.xtend.lib.annotations.FinalFieldsConstructorProcessor
	at org.eclipse.xtend.ide.macro.JdtBasedProcessorProvider.getProcessorInstance(JdtBasedProcessorProvider.java:60)
	at org.eclipse.xtend.core.macro.ActiveAnnotationContextProvider.lambda$0(ActiveAnnotationContextProvider.java:86)
	at org.eclipse.xtend.core.macro.ActiveAnnotationContextProvider.registerMacroAnnotations(ActiveAnnotationContextProvider.java:250)
	at org.eclipse.xtend.core.macro.ActiveAnnotationContextProvider.searchAnnotatedElements(ActiveAnnotationContextProvider.java:173)
	at org.eclipse.xtend.core.macro.ActiveAnnotationContextProvider.lambda$1(ActiveAnnotationContextProvider.java:166)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.xtend.core.macro.ActiveAnnotationContextProvider.searchAnnotatedElements(ActiveAnnotationContextProvider.java:168)
	at org.eclipse.xtend.core.macro.ActiveAnnotationContextProvider.computeContext(ActiveAnnotationContextProvider.java:131)
	at org.eclipse.xtend.core.jvmmodel.XtendJvmModelInferrer.infer(XtendJvmModelInferrer.java:188)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.installDerivedState(JvmModelAssociator.java:383)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.installDerivedState(DerivedStateAwareResource.java:244)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getContents(BatchLinkableResource.java:149)
	at org.eclipse.xtext.xbase.typesystem.internal.LogicalContainerAwareBatchTypeResolver.getEntryPoints(LogicalContainerAwareBatchTypeResolver.java:45)
	at org.eclipse.xtend.core.typesystem.TypeDeclarationAwareBatchTypeResolver.getEntryPoints(TypeDeclarationAwareBatchTypeResolver.java:57)
	at org.eclipse.xtext.xbase.typesystem.internal.DefaultBatchTypeResolver.getTypeResolver(DefaultBatchTypeResolver.java:87)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$1.get(CachingBatchTypeResolver.java:50)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$1.get(CachingBatchTypeResolver.java:1)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:79)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver.doResolveTypes(CachingBatchTypeResolver.java:47)
	at org.eclipse.xtext.xbase.typesystem.internal.AbstractBatchTypeResolver.resolveTypes(AbstractBatchTypeResolver.java:70)
	at org.eclipse.xtext.xbase.resource.BatchLinkingService.resolveBatched(BatchLinkingService.java:72)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.resolveLazyCrossReferences(BatchLinkableResource.java:166)
	at org.eclipse.xtext.EcoreUtil2.resolveLazyCrossReferences(EcoreUtil2.java:505)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.postParse(XtextDocumentReconcileStrategy.java:208)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.doReconcile(XtextDocumentReconcileStrategy.java:186)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.reconcile(XtextDocumentReconcileStrategy.java:91)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.doRun(XtextReconciler.java:457)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:371)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:1)
	at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:38)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:70)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.modify(XtextDocument.java:432)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.internalModify(XtextDocument.java:165)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.run(XtextReconciler.java:368)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: org.eclipse.xtend.lib.annotations.FinalFieldsConstructorProcessor
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.eclipse.xtend.ide.macro.JdtBasedProcessorProvider.getProcessorInstance(JdtBasedProcessorProvider.java:50)
	... 34 more
```
@LorenzoBettini  do you see that too.
will check if a clean build helps

**Comment by LorenzoBettini** [comment]
@cdietrich I'll check tomorrow. At the end of the setup a full clean build is triggered so automatic building shouldn't be off. Do you have custom user preferences?
