### ISSUE TITLE
Setup doesn't work anymore

### ISSUE THREAD

**Issue by merks** [eclipse/xtext#2225]
You have to be more careful with the modified modular targlet task because you are include a target platform resource specified by ID but that only works if that *.target is already in the workspace (and of course the clone must exist too):

![image](https://user-images.githubusercontent.com/208716/232292111-a4834c7d-e0d6-4484-971a-f73262abd05d.png)

Personally I would have gone for approach to generate the target from the *.target from targlet...

Easiest is to move all the targlet tasks after the import projects task.

Getting a clean build of out this whole deal seems challenging at best:
```
Updating duplicate resource: '/xtext-parent/org.eclipse.xtend.examples/projects/xtend-examples/xtend-gen/example6/.Movies.java._trace'.
ERROR: org.eclipse.core.resources code=75 Errors occurred during the build.
  at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:541)
  at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:420)
  at org.eclipse.oomph.setup.projects.impl.ProjectsBuildTaskImpl.perform(ProjectsBuildTaskImpl.java:525)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2382)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2407)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.xtext.ui.shared code=75 Errors running builder 'Xtext Project Builder' on project 'org.eclipse.xtend.ide.tests.data'.
  java.util.ConcurrentModificationException
    at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
    at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:783)
    at org.eclipse.xtext.ui.resource.Storage2UriMapperJavaImpl.getStorages(Storage2UriMapperJavaImpl.java:393)
    at org.eclipse.xtext.ui.resource.Storage2UriMapperImpl$2$1.apply(Storage2UriMapperImpl.java:139)
    at org.eclipse.xtext.ui.resource.Storage2UriMapperImpl$2$1.apply(Storage2UriMapperImpl.java:1)
    at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:614)
    at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
    at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
    at com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1333)
    at org.eclipse.xtext.ui.resource.Storage2UriMapperImpl.getStorages(Storage2UriMapperImpl.java:224)
    at org.eclipse.xtext.ui.resource.Storage2UriMapperImpl.getStorages(Storage2UriMapperImpl.java:218)
    at org.eclipse.xtext.builder.builderState.MarkerUpdaterImpl.processDelta(MarkerUpdaterImpl.java:73)
    at org.eclipse.xtext.builder.builderState.MarkerUpdaterImpl.updateMarkers(MarkerUpdaterImpl.java:64)
    at org.eclipse.xtext.builder.builderState.AbstractBuilderState.updateMarkers(AbstractBuilderState.java:137)
    at org.eclipse.xtext.builder.builderState.AbstractBuilderState.clean(AbstractBuilderState.java:215)
    at org.eclipse.xtext.builder.impl.XtextBuilder.doClean(XtextBuilder.java:730)
    at org.eclipse.xtext.builder.impl.XtextBuilder.addInfosFromTaskAndClean(XtextBuilder.java:644)
    at org.eclipse.xtext.builder.impl.XtextBuilder.clean(XtextBuilder.java:619)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1025)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:247)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:392)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:395)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:506)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:454)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:536)
    at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:524)
    at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:420)
    at org.eclipse.oomph.setup.projects.impl.ProjectsBuildTaskImpl.perform(ProjectsBuildTaskImpl.java:525)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2382)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2407)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
    at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
    at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by cdietrich** [comment]
meh. of course we just tested updating, not fresh clone. :(

**Comment by merks** [comment]
Yes, I know.  I have made this same exact same mistake!

**Comment by cdietrich** [comment]
@HannesWell  could you provide a patch?

**Comment by HannesWell** [comment]
Indeed I forgot this case sorry for that :/

> @HannesWell  could you provide a patch?

Yes, I will this evening when back home and will verify this works for a clean workspace.

> Easiest is to move all the targlet tasks after the import projects task.

Sounds like a good and simple solution, and should work fine since xtext does not use the targlets to import projects.

**Comment by merks** [comment]
How do I make errors like this go away?

![image](https://user-images.githubusercontent.com/208716/232309396-e4d1721f-3d15-4e57-8703-8a9aa7cfccbe.png)

**Comment by LorenzoBettini** [comment]
Mhh... The clean build task is meant to remove such errors.. isn't it a problem with the connection?

**Comment by merks** [comment]
I'm trying to remove my .m2e folder.  The errors remained after a clean build.  Then I tried turning off auto build and doing a clean without a rebuild.  Still the errors remain.  So clean does not really clean the errors as one would hope and expect...

Finally I try to delete the errors and turn back on auto build.  Now finally it's all clean:

![image](https://user-images.githubusercontent.com/208716/232311632-cef7eda1-30d5-48c1-9596-323f18a3e8c5.png)

It feels a like like voodoo is needed once something has gone wrong...

**Comment by LorenzoBettini** [comment]
You mean .m2, not .m2e right?

If you remove that folder with an open workspace then I guess some caching of m2e gets really angry. It never worked for me either.

But IIRC if you remove .m2 then rerun oomph tasks it works.

**Comment by merks** [comment]
Sorry, yes, .m2 is what I meant.  I couldn't remove it without exiting the IDE and restarting...

**Comment by HannesWell** [comment]
Thank you Ed for providing the fix!

> Personally I would have gone for approach to generate the target from the *.target from targlet...

I have to say that I was quite happy with the overall solution found in https://github.com/eclipse/xtext/pull/2213

> How do I make errors like this go away?

Would could help to force a re-download of Maven dependencies from M2E is
`Right-click -> Maven -> Update Project ...` and then select `Force Update of Snapshot/Releases` and click `OK`.

![grafik](https://user-images.githubusercontent.com/44067969/232341178-2cd58487-c1ca-4838-984e-c9e948dd2065.png)


> Sorry, yes, .m2 is what I meant. I couldn't remove it without exiting the IDE and restarting...

Yes, that's due to the strong file locking on Windows and because (at least some) jars are open on the classpath Windows prohibits their deletion.

**Comment by LorenzoBettini** [comment]
@HannesWell if you update the project you hit https://github.com/eclipse/xtext/issues/2227
