### ISSUE TITLE
java.lang.ClassCastException: LeafNode cannot be cast to CompositeNode

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext#2323]
Just hit the following exception while editing an `*.xtend` file:
![screenshot](https://user-images.githubusercontent.com/20393472/84269814-093a1900-ab2a-11ea-80ae-65068af69359.png)

```
org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy  - Parsing in reconciler failed.

java.lang.ClassCastException: org.eclipse.xtext.nodemodel.impl.LeafNode cannot be cast to org.eclipse.xtext.nodemodel.impl.CompositeNode
	at org.eclipse.xtext.xbase.parser.LookAheadPreservingNodeModelBuilder.replaceAndTransferLookAhead(LookAheadPreservingNodeModelBuilder.java:41)
	at org.eclipse.xtext.xbase.parser.TokenSequencePreservingPartialParsingHelper.reparse(TokenSequencePreservingPartialParsingHelper.java:127)
	at org.eclipse.xtext.parser.antlr.AbstractAntlrParser.doReparse(AbstractAntlrParser.java:139)
	at org.eclipse.xtext.parser.AbstractParser.reparse(AbstractParser.java:51)
	at org.eclipse.xtext.resource.XtextResource.update(XtextResource.java:266)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.doReconcile(XtextDocumentReconcileStrategy.java:183)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.reconcile(XtextDocumentReconcileStrategy.java:91)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.doRun(XtextReconciler.java:457)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.access$3(XtextReconciler.java:437)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:371)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:1)
	at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:38)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:70)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.modify(XtextDocument.java:432)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.internalModify(XtextDocument.java:165)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.run(XtextReconciler.java:368)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Versions:**
`Xtext SDK: 2.23.0.v20200608-0122`
`Xtend IDE: 2.23.0.v20200608-0122`

**Comment by imhotep82** [comment]
Would it be OK to file a PR that mitigates this issue? We could skip all non-composite Nodes as the lookahead can only be set on CompositeNode instances.
I encountered this error, but in my case it was a hidden node that caused the CCE.

**Comment by imhotep82** [comment]
@cdietrich @szarnekow

**Comment by cdietrich** [comment]
am not sure what the correct mitgation would be. lets see what sebastian says
