### ISSUE TITLE
Wrong version of emf.common during exec-maven-plugin and xtext-maven-plugin

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#2397]
I'm trying to build one of my (involved) DSL with Xtext 2.29.0.M2. I've updated the TP and the POM (I'm using the xtext-dev-bom).

During the execution of exec-maven-plugin (for running MWE2) I get this error:

```
0    [org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main()] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - IS_OSGI_RUNNING
java.lang.NoSuchFieldError: IS_OSGI_RUNNING
	at org.eclipse.emf.ecore.impl.EPackageRegistryImpl.createGlobalRegistry(EPackageRegistryImpl.java:55)
	at org.eclipse.emf.ecore.EPackage$Registry.<clinit>(EPackage.java:75)
	at org.eclipse.emf.mwe2.language.Mwe2StandaloneSetupGenerated.createInjectorAndDoEMFRegistration(Mwe2StandaloneSetupGenerated.java:38)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:75)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Similarly, when running xtext-maven-plugin:

```
Execution default of goal org.eclipse.xtext:xtext-maven-plugin:2.29.0.M2:generate
failed: An API incompatibility was encountered while executing
org.eclipse.xtext:xtext-maven-plugin:2.29.0.M2:generate:
java.lang.NoSuchFieldError: IS_OSGI_RUNNING
```

From what I understand, a new version of emf.ecore is used but an older version of emf.common, where that static field is not yet available.

In fact, version 2.20 of emf.ecore used to execute

```java
  public static EPackage.Registry createGlobalRegistry()
  {
    try
    {
      String className = System.getProperty("org.eclipse.emf.ecore.EPackage.Registry.INSTANCE");
      if (className == null)
      {
        if (EcorePlugin.getDefaultRegistryImplementation() != null)
        {
          return EcorePlugin.getDefaultRegistryImplementation();
        }
        else if (!EMFPlugin.IS_ECLIPSE_RUNNING)
...
```

while the version 2.28 of emf.ecore (which is the one being used) does

```java

  public static EPackage.Registry createGlobalRegistry()
  {
    try
    {
      String className = System.getProperty("org.eclipse.emf.ecore.EPackage.Registry.INSTANCE");
      if (className == null)
      {
        if (EcorePlugin.getDefaultRegistryImplementation() != null)
        {
          return EcorePlugin.getDefaultRegistryImplementation();
        }
        else if (!EMFPlugin.IS_OSGI_RUNNING)
...
```

The xtext-dev-bom specifies 2.17.0 for emf.common, which is extremely old. It looks like that version of emf.common is used together with emf.ecore 2.28 and BANG.

I'm not doing strange thing with the TP nor with the POM (hopefully).

If I redefine in my parent's POM dependencyManagement section the version of emf.common

```xml
			<dependency>
				<groupId>org.eclipse.emf</groupId>
				<artifactId>org.eclipse.emf.common</artifactId>
				<version>2.26.0</version>
			</dependency>
```

then mwe2 runs fine.

Similarly, I have to make this dependency explicit in the pluginManagement configuration of xtext-maven-plugin

```xml
				<plugin>
					<groupId>org.eclipse.xtext</groupId>
					<artifactId>xtext-maven-plugin</artifactId>
					<version>${xtextVersion}</version>
					<dependencies>
						<dependency>
							<groupId>org.eclipse.emf</groupId>
							<artifactId>org.eclipse.emf.common</artifactId>
							<version>2.26.0</version>
						</dependency>
					</dependencies>
				</plugin>
```

then also this plugin runs fine.

Why is the version of emf.common is so old in the BOM? Shouldn't the versions of emf in the BOM be updated?

**Comment by LorenzoBettini** [comment]
I think we can close this one now
