### ISSUE TITLE
Races in Storage2UriMapperJavaImpl

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2507]
we observe the following races in `Storage2UriMapperJavaImpl`

initialize race

```
Storage2UriMapperJavaImpl.clearCache(IJavaProject, Set<String>)
Storage2UriMapperJavaImpl.updateCache(IJavaProject)
Storage2UriMapperJavaImpl$3.run(IProgressMonitor)
Storage2UriMapperJavaImpl.doInitializeCache()	
Storage2UriMapperJavaImpl.initializeCache(boolean)
Storage2UriMapperJavaImplelementChanged(ElementChangedEvent)	
```

```
Storage2UriMapperJavaImpl.clearCache(IJavaProject, Set<String>)
Storage2UriMapperJavaImpl.updateCache(IJavaProject)
Storage2UriMapperJavaImpl$3.run(IProgressMonitor)
Workspace.run(ICoreRunnable, ISchedulingRule, int, IProgressMonitor)
Workspace.run(IWorkspaceRunnable, ISchedulingRule, int, IProgressMonitor)
Storage2UriMapperJavaImpl.doInitializeCache()	
Storage2UriMapperJavaImpl$2.run()	
Thread.run()	
```

read on non initialized

```
Storage2UriMapperJavaImpl.getCachedData(Storage2UriMapperJavaImplCopy.java)
	at .Storage2UriMapperJavaImp.getData(Storage2UriMapperJavaImplCopy.java)
	at Storage2UriMapperJavaImpl.getAllEntries(Storage2UriMapperJavaImplCopy.java)
	at org.eclipse.xtext.builder.impl.javasupport.JdtToBeBuiltComputer.updateProject(JdtToBeBuiltComputer.java:123)
```
might be called before
```
Storage2UriMapperJavaImpl.getCachedData(Storage2UriMapperJavaImplCopy.java)
	at Storage2UriMapperJavaImpl.updateCache(Storage2UriMapperJavaImplCopy.java)
	at Storage2UriMapperJavaImpl.elementChanged(Storage2UriMapperJavaImplCopy.java)
	at org.eclipse.jdt.internal.core.DeltaProcessor$3.run(DeltaProcessor.java:1755)
......
org.eclipse.core.internal.events.NotificationManager.NotifyJob.run(IProgressMonitor)
```

in both cases the clearCache will remove stuff that is in toBeKept with the same path/uriPrefix but a different PackageFragmentRootData.

this will lead to follow up errors as there is no IContainer for the Jar, and thus visibleContainer calls etc wont work

**Comment by stephan-herrmann** [comment]
As I'm currently affected by some ConcurrentModificationException in this area, I had a lock at `org.eclipse.xtext.ui.resource.Storage2UriMapperJavaImpl.getStorages(URI)` stumbling upon this:
```java
		// Pessimistic copy of the cachedPackageFragmentRootData
		Collection<PackageFragmentRootData> packageFragmentRootDatas;
		synchronized(cachedPackageFragmentRootData) {
			packageFragmentRootDatas = cachedPackageFragmentRootData.values();
		}
```
"Pessimistic copy" sounds good, but is there actually any local copy? `cachedPackageFragmentRootData` is a LinkedHashSet, where `values()` returns a **shared** `java.util.LinkedHashMap.LinkedValues` instance. So what is the advantage of this assignment?

Am I missing anything, or would wrapping the set of values with `Collections.unmodifiableCollection()` already help?

**Comment by stephan-herrmann** [comment]
> Am I missing anything, or would wrapping the set of values with `Collections.unmodifiableCollection()` already help?

With a number of dirty hacks I inserted a modification that does slightly more than the above, I made `cachedPackageFragmentRootData.values()` return smth like
```
Collections.unmodifiableCollection(new ArrayList<>(super.values()))
```

Only then I got a truly unshared collection. And voila, for my particular set of ConcurrentModificationException it seemed to fix it.

**Comment by stephan-herrmann** [comment]
Looking again my hacky fix actually resembles what was discussed in https://github.com/eclipse-archived/xtext-eclipse/pull/1873#pullrequestreview-1028205138 

Just wrapping in an unmodifiable collection was not a good idea. Simply creating a copy of the list is sufficient for me.
