### ISSUE TITLE
Problems with Xpand in TP and Oomph

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2676]
@merks do you have any idea what could cause this if i call oomph setup tasks with 2023-06 target platform for Xtext

```
ERROR: org.eclipse.oomph.targlets.core code=0 Resolution problems
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:919)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1232)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1092)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2382)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2407)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.oomph.targlets.core code=0 Problems resolving composed target 'xtext-latest'
    ERROR: org.eclipse.pde.core code=0 Problems occurred while resolving the target contents
      ERROR: org.eclipse.pde.core code=0 Problems loading repositories
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.xpand 0.0.0
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.xtend 0.0.0
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.xtend.typesystem.emf 0.0.0

Took 73 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.

```

from the target file:

```
		<location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
			<repository location="https://download.eclipse.org/modeling/m2t/xpand/updates/releases/R201605260315/"/>
			<unit id="org.eclipse.xpand" version="0.0.0"/>
			<unit id="org.eclipse.xtend" version="0.0.0"/>
			<unit id="org.eclipse.xtend.typesystem.emf" version="0.0.0"/>
		</location>
```

**Comment by merks** [comment]
No, now you are getting into the PDE domain...  Does this thing resolve if you open that file in the workspace?  Is it perhaps again a problem of it not re-resolving until you do it manually?

**Comment by cdietrich** [comment]
no i just do a perform setup tasks and it fails. 
cannot test manual resolve currently cause I-Builds repo from platform seems broken.

**Comment by cdietrich** [comment]
as said manual resilve does not work cause 20230522 platfrom artifacts can currently not be found.
will retry tomorrow.
the xpand problem i saw multiple times over the last weeks

**Comment by cdietrich** [comment]
might be related to en/disabling mirrors

**Comment by cdietrich** [comment]
no problem also happens with mirrors off.
manually loading tp seems to help

**Comment by merks** [comment]
Did you start using the sequence number thing yet?

**Comment by cdietrich** [comment]
yes but that does not help

**Comment by cdietrich** [comment]
I did not test fresh but see it on server machines on perform setup tasks

**Comment by cdietrich** [comment]
hmmm new player in town :(

**Comment by merks** [comment]
It works fine in the repository explorer.  Probably a network glitch.

I think a hard decision needs to be made sooner rather than later.   Either the Xpand project should be archived and all dependencies on it should be eliminated, or there should be a build to produce maintenance versions.  It's not a large project and setting up a build doesn't seem like rocket science.  But it doesn't make sense for me to help if the plan is to eliminate dependencies, which would seem like the better solution.

The first time there is some CVE in the project or one of its dependencies, the house of cards will come crumbling down.

**Comment by cdietrich** [comment]
yes. dont know if anything other in eclipse uses old xpand based generator besides xpect

**Comment by cdietrich** [comment]
problem is gone with the xpand removal from tp
