### ISSUE TITLE
NullPointerException when using WorkspaceFolders in LSP initialization request

### ISSUE THREAD

**Issue by jnt0r** [eclipse/xtext#2697]
As soon as I set the WorkspaceFolders Property in the LSP initialization request, I get a NullPointerException in the xtext LSP server.
I tried different values for the property in different formats, but I always get the same exception.

```
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.eclipse.xtext.ide.server.concurrent.AbstractRequest.logAndCompleteExceptionally(AbstractRequest.java:73)
	at org.eclipse.xtext.ide.server.concurrent.WriteRequest.run(WriteRequest.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Caused by: java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at org.eclipse.xtext.resource.impl.ChunkedResourceDescriptions.setContainer(ChunkedResourceDescriptions.java:92)
	at org.eclipse.xtext.ide.server.ProjectManager.createNewResourceSet(ProjectManager.java:145)
	at org.eclipse.xtext.ide.server.ProjectManager.createFreshResourceSet(ProjectManager.java:155)
	at org.eclipse.xtext.ide.server.ProjectManager.newBuildRequest(ProjectManager.java:124)
	at org.eclipse.xtext.ide.server.ProjectManager.doBuild(ProjectManager.java:106)
	at org.eclipse.xtext.ide.server.ProjectManager.doInitialBuild(ProjectManager.java:98)
	at org.eclipse.xtext.ide.server.BuildManager.doInitialBuild(BuildManager.java:164)
	at org.eclipse.xtext.ide.server.WorkspaceManager.refreshWorkspaceConfig(WorkspaceManager.java:254)
	at org.eclipse.xtext.ide.server.WorkspaceManager.initialize(WorkspaceManager.java:173)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$0(LanguageServerImpl.java:239)
	at org.eclipse.xtext.ide.server.concurrent.WriteRequest.run(WriteRequest.java:50)
	... 5 more
```

**Comment by cdietrich** [comment]
Can you provide a reproducer unit test

**Comment by jnt0r** [comment]
I try to. I don't have a working xtext workspace yet and have to set it up first.
I tested it with the simple greetings starter DSL and the ballerina/lsp4intellij Plugin (newest version from master).

**Comment by cdietrich** [comment]
you should be able to create a test in a new mydsl project

**Comment by jnt0r** [comment]
I created a sample project https://github.com/jnt0r/xtext-npe-reproducable
Test is located here https://github.com/jnt0r/xtext-npe-reproducable/blob/master/org.xtext.example.mydsl.tests/src/org/xtext/example/mydsl/tests/MyLSPWorkspaceFoldersTest.java

I created multiple tests and figured out that it seems to depend on the name of the WorkspaceFolder.
Is this field really required? Wouldn't it be more convenient to throw dedicated errors instead of a NullPointerException?
I read that the WorkspaceFolder name defaults to the name of the specified folder in the provided uri.

**Comment by cdietrich** [comment]
Xtext try’s to provide a project name from a folder name and currently we at lease need some name
I don’t know why we don’t throw a dedicated error. Needs to be looked at

**Comment by cdietrich** [comment]
Reading 
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspaceFolder
I don’t see the name to be optional

**Comment by cdietrich** [comment]
maybe should be fixed in lsp4j

**Comment by cdietrich** [comment]
created https://github.com/eclipse-lsp4j/lsp4j/issues/741

**Comment by jnt0r** [comment]
https://github.com/eclipse-lsp4j/lsp4j/issues/741 has been fixed and closed.
