### ISSUE TITLE
Cannot Launch CliWizardIntegrationTest as java app

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#3018]
<img width="483" alt="grafik" src="https://github.com/eclipse/xtext/assets/238736/cda9205e-365b-4f7d-8f85-ef120cacfb1b">

**Comment by cdietrich** [comment]
```
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.m2e.pde.connector.TychoLifecycleMapping$EclipsePluginProjectConfigurator
	at org.eclipse.m2e.pde.connector.TychoLifecycleMapping.getProjectConfigurators(TychoLifecycleMapping.java:68)
	at org.eclipse.m2e.jdt.internal.DefaultClasspathManagerDelegate.getJavaProjectConfigurators(DefaultClasspathManagerDelegate.java:79)
	at org.eclipse.m2e.jdt.internal.DefaultClasspathManagerDelegate.populateClasspath(DefaultClasspathManagerDelegate.java:66)
	at org.eclipse.m2e.jdt.internal.BuildPathManager.getClasspath(BuildPathManager.java:239)
	at org.eclipse.m2e.jdt.internal.BuildPathManager.getClasspath(BuildPathManager.java:360)
	at org.eclipse.m2e.jdt.internal.launch.MavenRuntimeClasspathProvider.addMavenClasspathEntries(MavenRuntimeClasspathProvider.java:214)
	at org.eclipse.m2e.jdt.internal.launch.MavenRuntimeClasspathProvider.resolveClasspath0(MavenRuntimeClasspathProvider.java:187)
	at org.eclipse.m2e.jdt.internal.launch.MavenRuntimeClasspathProvider.lambda$2(MavenRuntimeClasspathProvider.java:170)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:458)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:339)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:278)
	at org.eclipse.m2e.jdt.internal.launch.MavenRuntimeClasspathProvider.resolveClasspath(MavenRuntimeClasspathProvider.java:170)
	at org.eclipse.jdt.internal.launching.RuntimeClasspathProvider.resolveClasspath(RuntimeClasspathProvider.java:68)
	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspath(JavaRuntime.java:1668)
	at org.eclipse.jdt.launching.AbstractJavaLaunchConfigurationDelegate.getClasspath(AbstractJavaLaunchConfigurationDelegate.java:432)
	at org.eclipse.jdt.launching.JavaLaunchDelegate.getVMRunnerConfiguration(JavaLaunchDelegate.java:96)
	at org.eclipse.jdt.launching.JavaLaunchDelegate.launch(JavaLaunchDelegate.java:160)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:805)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1038)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$1.run(DebugUIPlugin.java:1241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator [in thread "Worker-75: Launching CliWizardIntegrationTest"]
	... 22 more
```

**Comment by cdietrich** [comment]
@HannesWell any idea?

**Comment by szarnekow** [comment]
@cdietrich I think you're seeing the same issue as described here. 
github.com/eclipse-m2e/m2e-core/issues/1743

**Comment by szarnekow** [comment]
Quoting @HannesWell 

> This looks like a duplicate of https://github.com/eclipse-m2e/m2e-core/issues/1735, which is already fixed.
> 
> Please try the latest snapshot at https://download.eclipse.org/technology/m2e/snapshots/latest/

**Comment by LorenzoBettini** [comment]
@cdietrich If you put that p2 repository in the Oomph file, then yes. If you add it manually in Eclipse and install it manually, I don't think Oomph will use the p2 repository you added manually, but I think it will not try to revert to an old version.

I forgot to mention I also experienced this problem a few days ago, and simply reverted it to a working configuration. I'll wait for the next Eclipse milestone where the fixed m2e should already be there.

**Comment by HannesWell** [comment]
> Quoting @HannesWell
> 
> > This looks like a duplicate of [eclipse-m2e/m2e-core#1735](https://github.com/eclipse-m2e/m2e-core/issues/1735), which is already fixed.
> > Please try the latest snapshot at https://download.eclipse.org/technology/m2e/snapshots/latest/

Yes exactly.

> Will oomph pick that with m2

A state of m2e that contains the fix is already contributed to SimRel, I'll probably update it again in time, but M2 will definitely contain it. But we have also reverted the causing change in Equinox and JDT.

**Comment by HannesWell** [comment]
> @cdietrich If you put that p2 repository in the Oomph file, then yes. If you add it manually in Eclipse and install it manually, I don't think Oomph will use the p2 repository you added manually, but I think it will not try to revert to an old version.

Yes, you can for example you can temporarily add a `P2Directory` task with the repo to your `installation.setup`:
```
<?xml version="1.0" encoding="UTF-8"?>
<setup.p2:P2Task
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:setup.p2="http://www.eclipse.org/oomph/setup/p2/1.0">
  <repository
      url="https://download.eclipse.org/technology/m2e/snapshots/2.6.1/"/>
</setup.p2:P2Task>
```
Of course the workspace and user setup works too but would have a correspondingly different scope where it is considered.

**Comment by LorenzoBettini** [comment]
> > @HannesWell so this fix will be in the next M of Eclipse, right?
> 
> Yes, that's right.

I seem to understand that M2 has been promoted, so we are now fine, aren't we? @HannesWell

**Comment by HannesWell** [comment]
> > > @HannesWell so this fix will be in the next M of Eclipse, right?
> > 
> > 
> > Yes, that's right.
> 
> I seem to understand that M2 has been promoted, so we are now fine, aren't we? @HannesWell

M2 has been staged and AFAIK it will be made visible/available tomorrow.
But for me everything is fine already. We just have to wait until the fix trickles down.
