### ISSUE TITLE
org.eclipse.xtend.core.tests.compiler.XbaseIntegrationTest.testAnonymousConstructorVarArgs_* fail on latest

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#3033]
org.eclipse.xtend.core.tests.compiler.XbaseIntegrationTest.testAnonymousConstructorVarArgs_02
and similar fail on latest

todo: check why
also check if there was something changed in JDT

**Comment by cdietrich** [comment]
```
Caused by: java.lang.NullPointerException: Cannot read the array length because the return value of "org.eclipse.jdt.internal.compiler.lookup.ReferenceBinding.syntheticOuterLocalVariables()" is null
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.retrieveLocalType(CodeStream.java:7686)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.pushTypeBinding(CodeStream.java:7705)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.aload_3(CodeStream.java:394)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.load(CodeStream.java:6284)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.load(CodeStream.java:6186)
	at org.eclipse.jdt.internal.compiler.ast.SingleNameReference.generateCode(SingleNameReference.java:520)
	at org.eclipse.jdt.internal.compiler.ast.Statement.generateArguments(Statement.java:421)
	at org.eclipse.jdt.internal.compiler.ast.ExplicitConstructorCall.generateCode(ExplicitConstructorCall.java:177)
	at org.eclipse.jdt.internal.compiler.ast.ConstructorDeclaration.internalGenerateCode(ConstructorDeclaration.java:441)
	at org.eclipse.jdt.internal.compiler.ast.ConstructorDeclaration.generateCode(ConstructorDeclaration.java:312)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:762)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:806)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.generateCode(QualifiedAllocationExpression.java:248)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.generateCode(MessageSend.java:618)
	at org.eclipse.jdt.internal.compiler.ast.Statement.generateArguments(Statement.java:440)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.generateCode(MessageSend.java:625)
	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.generateCode(ReturnStatement.java:234)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:388)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:324)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:762)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:832)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:412)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:915)
	at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:574)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:474)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:425)
```

**Comment by cdietrich** [comment]
@srikanth-sankaran  does this ring a bell?

**Comment by cdietrich** [comment]
class compiled

```
package foo;

import testdata.ClassWithVarArgs;

@SuppressWarnings("all")
public class Test {
  public Object foo() throws Exception {
    return Boolean.valueOf(new ClassWithVarArgs(1, "", "") {
    }.isVarArgConstructor());
  }
}
```

dependency:

```
public class ClassWithVarArgs {

	private boolean varArgConstructor;
	private boolean defaultConstructor;

	public ClassWithVarArgs() {
		defaultConstructor = true;
	}
	
	public ClassWithVarArgs(int i, String... strings) {
		this.varArgConstructor = true;
	}
	
	public ClassWithVarArgs(int i, String s1, String s2) {
		this.varArgConstructor = false;
	}
	
	public List<String> stringsToList(String... strings) {
		if (strings == null)
			return null;
		return Lists.newArrayList(strings);
	}
	
	public List<String> stringsToList2(String firstArg, String... strings) {
		if (strings == null)
			return null;
		final ArrayList<String> result = Lists.newArrayList(firstArg);
		result.addAll(Lists.newArrayList(strings));
		return result;
	}
	
	@SuppressWarnings("unchecked")
	public <T> List<T> toList(T... args) {
		return Lists.newArrayList(args);
	}
	
	@SuppressWarnings("unchecked")
	public <T extends Number> List<T> toNumberList(T... args) {
		return Lists.newArrayList(args);
	}
	
	public List<String> stringsToList(String s1, String s2) {
		return Lists.newArrayList("foo", s1, s2);
	}
	
	public boolean isVarArgConstructor() {
		return varArgConstructor;
	}
	
	public boolean isDefaultConstructor() {
		return defaultConstructor;
	}
	
	public String logInfo(String msg) {
		return String.format("logInfo(%s)", msg);
	}

	public String logInfo(String msg, Object... args) {
		return String.format("logInfo(%s, args...)", msg);
	}
	
	public String logInfo2(String msg) {
		return String.format("logInfo2(%s)", msg);
	}

	public String logInfo2(String msg, String param1) {
		return String.format("logInfo2(%s, %s)", msg, param1);
	}
	
	public String logInfo2(String msg, String param1, String param2) {
		return String.format("logInfo2(%s, %s, %s)", msg, param1, param2);
	}
	
	public String logInfo2(String msg, Object... args) {
		return String.format("logInfo2(%s, args...)", msg);
	}
	
	private List<String> values;
	
	public void setValues(String ... values) {
		this.values = stringsToList(values);
	}
	
	public List<String> getValues() {
		return values;
	}
	
}
```

**Comment by srikanth-sankaran** [comment]
> @srikanth-sankaran does this ring a bell?

I am happy to take a look - could you raise a ticket against jdt.core with a reproducer please ? 

https://github.com/eclipse-jdt/eclipse.jdt.core/issues

**Comment by cdietrich** [comment]
@srikanth-sankaran i am not sure how easy it is to create a reproducer and if i can find the time.
is there any starters for "compile these bunch" tests in jdt?

**Comment by cdietrich** [comment]
i also cannot reproduce this in a non plugin test yet

maybe @szarnekow has an idea

**Comment by cdietrich** [comment]
created https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2428

**Comment by cdietrich** [comment]
@szarnekow @LorenzoBettini maybe we should try to retackle this

**Comment by LorenzoBettini** [comment]
Yes, I think it makes no sense to use Java 5 nowadays.

@cdietrich if you still have a workspace with the failure, could you please check whether increasing Java version fixes the problem?

**Comment by LorenzoBettini** [comment]
It should be enough to open the target file manually and resolve that.

However, I seem to understand that https://www.eclipse.org/downloads/download.php?file=/eclipse/updates/4.32-I-builds/I20240508-1800/plugins/org.eclipse.jdt.core.compiler.batch.source_3.38.0.v20240508-1436.jar is more recent than the one used in the failing CI. I'll try to trigger rebuild.

**Comment by srikanth-sankaran** [comment]
I beleive I build https://download.eclipse.org/eclipse/downloads/drops4/I20240508-1800/ has the fix

**Comment by LorenzoBettini** [comment]
Restarting jobs fixed the problem with the fixed `jdt.core.compiler`.

We still have failures in macOS:

```
Failures: 
org.eclipse.xtend.ide.tests.compiler.JavaVersionSettingTest.testCompileWithJava6
  Run 1: JavaVersionSettingTest.testCompileWithJava6:130->assertNoErrors:160->Assert.assertFalse:65->Assert.assertTrue:42->Assert.fail:89 Couldn't find the mandatory library 'org.eclipse.xtext.xbase.lib' 2.8.0 or higher on the project's classpath.
```

maybe it's just a time problem, in fact, this other one is a flake but it succeeds in the end:

```
Flakes: 
org.eclipse.xtend.ide.tests.compiler.JavaVersionSettingTest.testCompileWithJava5
  Run 1: JavaVersionSettingTest.testCompileWithJava5:95->assertNoErrors:160->Assert.assertFalse:65->Assert.assertTrue:42->Assert.fail:89 Couldn't find the mandatory library 'org.eclipse.xtext.xbase.lib' 2.8.0 or higher on the project's classpath.
  Run 2: JavaVersionSettingTest.testCompileWithJava5:95->assertNoErrors:160->Assert.assertFalse:65->Assert.assertTrue:42->Assert.fail:89 Couldn't find the mandatory library 'org.eclipse.xtext.xbase.lib' 2.8.0 or higher on the project's classpath.
  Run 3: PASS
```

I'll try to re-run the job.
