### ISSUE TITLE
Huge amount of time to start a plug-in test

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#3060]
I've seen that yesterday on a macOS and today on a Linux machine, updated both with the latest IDE and TP: it takes about a minute to start a JUnit plug-in test in our workspace; during the wait, Java is eating all the CPU.

Am I the only one seeing this?

**Comment by cdietrich** [comment]
i also saw something like that. but didnt profile yet

**Comment by LorenzoBettini** [comment]
I've seen it since yesterday...

I don't know if this is related:

```
!ENTRY org.eclipse.lsp4e 4 0 2024-05-22 15:11:22.732
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.lsp4e [280]
  Unresolved requirement: Require-Bundle: org.eclipse.lsp4j.jsonrpc; bundle-version="[0.22.0,0.23.0)"
    -> Bundle-SymbolicName: org.eclipse.lsp4j.jsonrpc; bundle-version="0.22.0.v20240213-2011"
       org.eclipse.lsp4j.jsonrpc [286]
         Unresolved requirement: Import-Package: com.google.gson.annotations; version="[2.9.1,2.11.0)"
  Unresolved requirement: Require-Bundle: org.eclipse.lsp4j; bundle-version="[0.22.0,0.23.0)"
    -> Bundle-SymbolicName: org.eclipse.lsp4j; bundle-version="0.22.0.v20240213-2011"
       org.eclipse.lsp4j [282]
         Unresolved requirement: Import-Package: com.google.gson.annotations; version="[2.9.1,2.11.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:493)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2074)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:143)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2065)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2005)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1968)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1884)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
```

In particular this one `com.google.gson.annotations; version="[2.9.1,2.11.0)"` which we updated yesterday?

**Comment by LorenzoBettini** [comment]
And it's only for plugin tests: starting another instance of Eclipse from the workspace doesn't take that long

**Comment by cdietrich** [comment]
the new lsp4j was released yesterday and i updated the targets
so oomphing should solve

**Comment by LorenzoBettini** [comment]
I've already oomphed but the error above says that an older version of gson is required, while yesterday it was upgraded.

**Comment by cdietrich** [comment]
change was yesterday evening.
with that one

lsp4j 0.23.1, gson 2.11.0

**Comment by cdietrich** [comment]
=> where is your old
Bundle-SymbolicName: org.eclipse.lsp4j.jsonrpc; bundle-version="0.22.0.v20240213-2011"
in the tp?

**Comment by cdietrich** [comment]
maybe there is still old lsp4e in 2024-06

**Comment by LorenzoBettini** [comment]
I seem to understand it's m2e.editor and so wildwebdeveloper that want an older version

**Comment by cdietrich** [comment]
hmmmm am not sure if there is still bump prs open for them.

**Comment by LorenzoBettini** [comment]
I refreshed the TP from scratch, but I still see these errors and the UI test takes minutes to start:

```
!ENTRY org.eclipse.lsp4e 4 0 2024-05-23 11:01:13.686
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.lsp4e [280]
  Unresolved requirement: Require-Bundle: org.eclipse.lsp4j; bundle-version="[0.22.0,0.23.0)"
    -> Bundle-SymbolicName: org.eclipse.lsp4j; bundle-version="0.22.0.v20240213-2011"
       org.eclipse.lsp4j [282]
         Unresolved requirement: Import-Package: com.google.gson.annotations; version="[2.9.1,2.11.0)"
  Unresolved requirement: Require-Bundle: org.eclipse.lsp4j.jsonrpc; bundle-version="[0.22.0,0.23.0)"
    -> Bundle-SymbolicName: org.eclipse.lsp4j.jsonrpc; bundle-version="0.22.0.v20240213-2011"
       org.eclipse.lsp4j.jsonrpc [286]
         Unresolved requirement: Import-Package: com.google.gson.annotations; version="[2.9.1,2.11.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:493)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2074)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:143)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2065)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2005)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1968)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1884)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.

!ENTRY org.eclipse.wildwebdeveloper.xml 4 0 2024-05-23 11:01:14.485
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.wildwebdeveloper.xml [396]
  Unresolved requirement: Require-Bundle: org.eclipse.lsp4j; bundle-version="0.9.0"
    -> Bundle-SymbolicName: org.eclipse.lsp4j; bundle-version="0.22.0.v20240213-2011"
       org.eclipse.lsp4j [282]
         Unresolved requirement: Import-Package: com.google.gson.annotations; version="[2.9.1,2.11.0)"
  Unresolved requirement: Require-Bundle: org.eclipse.lsp4j.jsonrpc
    -> Bundle-SymbolicName: org.eclipse.lsp4j.jsonrpc; bundle-version="0.22.0.v20240213-2011"
       org.eclipse.lsp4j.jsonrpc [286]
         Unresolved requirement: Import-Package: com.google.gson.annotations; version="[2.9.1,2.11.0)"
  Unresolved requirement: Require-Bundle: org.eclipse.lsp4e; bundle-version="0.16.0"
    -> Bundle-SymbolicName: org.eclipse.lsp4e; bundle-version="0.18.6.202403050753"; singleton:="true"
       org.eclipse.lsp4e [280]
         Unresolved requirement: Require-Bundle: org.eclipse.lsp4j; bundle-version="[0.22.0,0.23.0)"
           -> Bundle-SymbolicName: org.eclipse.lsp4j; bundle-version="0.22.0.v20240213-2011"
         Unresolved requirement: Require-Bundle: org.eclipse.lsp4j.jsonrpc; bundle-version="[0.22.0,0.23.0)"
           -> Bundle-SymbolicName: org.eclipse.lsp4j.jsonrpc; bundle-version="0.22.0.v20240213-2011"

	at org.eclipse.osgi.container.Module.start(Module.java:493)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2074)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:143)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2065)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2005)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1968)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1884)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
```

I thought that the latest wildwebdeveloper was contributed yesterday

**Comment by cdietrich** [comment]
there is still : org.eclipse.wildwebdeveloper.xml

**Comment by LorenzoBettini** [comment]
> there is still : org.eclipse.wildwebdeveloper.xml
> 
> is 202406M3 already "live"

mh... maybe not! I forgot we don't use the "staging" repository in the TP.

**Comment by cdietrich** [comment]
is this pressing or can you live with a local workaround?

**Comment by LorenzoBettini** [comment]
> is this pressing or can you live with a local workaround?

That was meant to be a local workaround.
I leave this here in case it can help if someone else experiences this.
I don't think this is required in the CI: there's no delay in the CI in that respect.
