### ISSUE TITLE
More Problems with upstream JDT changes

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#3113]
e.g.
org.eclipse.xtext.purexbase.tests.XbaseIntegrationTest

**Comment by cdietrich** [comment]
```
java.lang.AssertionError: java.lang.IllegalArgumentException: Java code compiled with errors:
Pb(1109) Compiling for Java version '1.6' is no longer supported. Minimal supported version is '1.8'

Code was:
=========
import java.util.List;
import testdata.ClassWithVarArgs;

@SuppressWarnings("all")
public class MyFile {
  public List<String> myMethod() throws Throwable {
    return new ClassWithVarArgs().stringsToList("s1", "s2", "s3");
  }
}
=========

	at org.eclipse.xtext.xbase.testing.CompilationTestHelper$Result.doCompile(CompilationTestHelper.java:613)
	at org.eclipse.xtext.xbase.testing.CompilationTestHelper$Result.getCompiledClasses(CompilationTestHelper.java:443)
	at org.eclipse.xtext.xbase.testing.CompilationTestHelper$Result.getCompiledClass(CompilationTestHelper.java:516)
	at org.eclipse.xtext.purexbase.tests.XbaseIntegrationTest$1.accept(XbaseIntegrationTest.java:41)
	at org.eclipse.xtext.purexbase.tests.XbaseIntegrationTest$1.accept(XbaseIntegrationTest.java:1)
	at org.eclipse.xtext.xbase.testing.CompilationTestHelper.compile(CompilationTestHelper.java:252)
	at org.eclipse.xtext.xbase.testing.CompilationTestHelper.compile(CompilationTestHelper.java:201)
	at org.eclipse.xtext.purexbase.tests.XbaseIntegrationTest.invokeXbaseExpression(XbaseIntegrationTest.java:37)
	at org.eclipse.xtext.xbase.testing.evaluation.AbstractXbaseEvaluationTest.assertEvaluatesTo(AbstractXbaseEvaluationTest.java:5346)
	at org.eclipse.xtext.xbase.testing.evaluation.AbstractXbaseEvaluationTest.testMethodVarArgs_04(AbstractXbaseEvaluationTest.java:3687)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.eclipse.xtext.testing.XtextRunner$1.evaluate(XtextRunner.java:50)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.IllegalArgumentException: Java code compiled with errors:
Pb(1109) Compiling for Java version '1.6' is no longer supported. Minimal supported version is '1.8'

Code was:
=========
import java.util.List;
import testdata.ClassWithVarArgs;

@SuppressWarnings("all")
public class MyFile {
  public List<String> myMethod() throws Throwable {
    return new ClassWithVarArgs().stringsToList("s1", "s2", "s3");
  }
}
=========

	at org.eclipse.xtext.xbase.testing.OnTheFlyJavaCompiler2.compileToClasses(OnTheFlyJavaCompiler2.java:137)
	at org.eclipse.xtext.xbase.testing.CompilationTestHelper$Result.doCompile(CompilationTestHelper.java:608)
	... 35 more

```

see also https://github.com/eclipse/xtext/issues/2344

**Comment by cdietrich** [comment]
e.g
org.eclipse.xtext.xbase.testing.OnTheFlyJavaCompiler2.OnTheFlyJavaCompiler2(ClassLoader)

**Comment by cdietrich** [comment]
there is also more places mentioning JAVA5 and < JAVA8

**Comment by cdietrich** [comment]
also should we immediately go to JAVA11 whilst we are at it.

**Comment by cdietrich** [comment]
naive attempts lead to

Caused by: java.lang.Error: Unresolved compilation problems: 
	Type mismatch: cannot convert from java.lang.String to foo.String
	Type mismatch: cannot convert from java.lang.String to foo.String
	
	:(

**Comment by cdietrich** [comment]
also o ton of tests does not seem to work from eclipse ...
=> hard to analyze and fix.
have pushed a rough experiment to cd-jdt-old-java-purge branch.
am off now

**Comment by cdietrich** [comment]
see also very old attempts
https://github.com/eclipse/xtext-extras/tree/cd_extras_issue113
https://github.com/eclipse/xtext-eclipse/tree/cd_extras_issue113
https://github.com/eclipse/xtext-xtend/tree/cd_extras_issue113

**Comment by cdietrich** [comment]
@szarnekow i fear we at least need some direction if
e.g. we just adjust the test expectations.
e.g. as i did in https://github.com/eclipse/xtext-extras/commit/2cfb83875bafe207490a8c3b101a917ab4c1006c#diff-c9df00b7aebd9a5f1294c646166e8af7c27f38954189ae4e328e2dd88ce37447

**Comment by cdietrich** [comment]
from some tests there is already a java 8 variant
e.g.
CompilerBug465058Test
so i assume we dont need both

**Comment by szarnekow** [comment]
> have pushed a rough experiment to cd-jdt-old-java-purge branch.
> https://ci.eclipse.org/xtext/job/xtext/job/cd-jdt-old-java-purge/2/

Investigating.

**Comment by cdietrich** [comment]
@szarnekow 
see also https://ci.eclipse.org/xtext/job/xtext/job/cd-more-experiments/

**Comment by szarnekow** [comment]
Pushed some test updates and interpreter fixes. Now looking into usages of JavaVersion

**Comment by szarnekow** [comment]
Yet more updates pushed. The reasonable thing to do is to migrate test expectations to Java8 compliant code and log errors when the compliance level is attempted to be set to something lower than Java 8.

WDYT?

**Comment by cdietrich** [comment]
ok lets see how much is left with that
we still need to look into the preference changes i did on the other branch
(might be in the "usages < 8" list you mentioned before

**Comment by cdietrich** [comment]
@szarnekow are you still working on this. can take care of some more compilerbugxxxx tests tomorrow.

**Comment by cdietrich** [comment]
pushed a first bunch

**Comment by szarnekow** [comment]
I have a few minutes to kill and will take a stab of some more now.

**Comment by cdietrich** [comment]
TODO:
log errors in
GeneratorConfig/OnTheFlyCompiler/CompilerConfiguration/....... setJavaVersion
?

**Comment by cdietrich** [comment]
Fixed
