### ISSUE TITLE
Tycho + arm64 + target platform config

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#3142]
wo dont have
arm64
mac 
in the tp list in
new project wizard and domain model.

when building domain am getting

```
[WARNING] Your build environment {osgi.os=macosx, osgi.ws=cocoa, osgi.arch=aarch64} does not match any of the configured target environments [macosx/cocoa/x86_64, win32/win32/x86_64, linux/gtk/x86_64]. Test execution might be inconsistent

```

**Comment by cdietrich** [comment]
leads to follow up
Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.SWTError cannot be found by org.eclipse.ui.workbench_3.133.0.v20240724-1640
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:562)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:557)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:434)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:174)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 33 more

**Comment by LorenzoBettini** [comment]
That's right! The project wizard and domain model must be adapted to build on the arm.

If we rely on the latest Eclipse arm is supported on Linux and mac (and maybe Windows?)
