### ISSUE TITLE
fix xtext/xtext-languageserver-example

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#3149]
xtext/xtext-languageserver-example does no longer build

- node, vsce and likely many other dependencies are hopelessly outdated

**Comment by cdietrich** [comment]
> Task :vscode-extension:vscodeExtension FAILED
/Users/dietrich/git/xtext-languageserver-example/node_modules/undici/lib/web/fetch/response.js:542
  ReadableStream
  ^

ReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/Users/dietrich/git/xtext-languageserver-example/node_modules/undici/lib/web/fetch/response.js:542:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/dietrich/git/xtext-languageserver-example/node_modules/undici/lib/web/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

FAILURE: Build failed with an exception.

**Comment by cdietrich** [comment]
have pushed just a minimal fix.
no real cleanup

**Comment by cdietrich** [comment]
done
