### ISSUE TITLE
Investigate failing example tests

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#3193]
https://github.com/xtext/xtext-reference-projects/actions/runs/10860556518

No idea why 

(assertion for unit tests seems to fail)

xtend examples fail too
https://github.com/xtext/xtext-reference-projects/actions/runs/10859774718/job/30139568409

(also test fails here)

**Comment by cdietrich** [comment]
@LorenzoBettini wonder if we can archive the screenshots somehow if swtbot takes any

**Comment by cdietrich** [comment]
at least locally i see 2 launch configs for the xtend anno example. no idea why

**Comment by cdietrich** [comment]
```
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: NoClassDefFoundError: org/eclipse/core/runtime/Plugin
  at OnTheFlyJavaCompiler2.<init>(OnTheFlyJavaCompiler2.java:48)
  at OnTheFlyJavaCompiler2.class(OnTheFlyJavaCompiler2.java:37)
  at CompilationTestHelper.javaCompiler(CompilationTestHelper.java:157)
      \_ for field javaCompiler
  at XtendCompilerTester.compilationTestHelper(XtendCompilerTester.java:43)
      \_ for field compilationTestHelper
  while locating XtendCompilerTester

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
CompilationTestHelper: "org.eclipse.xtext.xbase.testing.CompilationTestHelper"
OnTheFlyJavaCompiler2: "org.eclipse.xtext.xbase.testing.OnTheFlyJavaCompiler2"
XtendCompilerTester:   "org.eclipse.xtend.core.compiler.batch.XtendCompilerTester"
========================
End of classname legend:
========================

	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186)
	at org.eclipse.xtend.core.compiler.batch.XtendCompilerTester.newXtendCompilerTester(XtendCompilerTester.java:56)
	at lazy.LazyTest.<init>(LazyTest.java:19)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
	at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/core/runtime/Plugin
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at org.eclipse.xtext.xbase.testing.InMemoryJavaCompiler.findInlineJsrBytecode(InMemoryJavaCompiler.java:226)
	at org.eclipse.xtext.xbase.testing.InMemoryJavaCompiler.<clinit>(InMemoryJavaCompiler.java:223)
	at org.eclipse.xtext.xbase.testing.OnTheFlyJavaCompiler2.<init>(OnTheFlyJavaCompiler2.java:52)
	at org.eclipse.xtext.xbase.testing.OnTheFlyJavaCompiler2.<init>(OnTheFlyJavaCompiler2.java:48)
	at org.eclipse.xtext.xbase.testing.OnTheFlyJavaCompiler2$$FastClassByGuice$$120790ea.GUICE$TRAMPOLINE(<generated>)
	at org.eclipse.xtext.xbase.testing.OnTheFlyJavaCompiler2$$FastClassByGuice$$120790ea.apply(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
	... 30 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.core.runtime.Plugin
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 63 more

```

**Comment by cdietrich** [comment]
=> looks like the workaround transitive dependeny does not work for some reason?

**Comment by cdietrich** [comment]
@szarnekow do you have an idea?

**Comment by cdietrich** [comment]
hmmm explicitely adding leads to

com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: NoClassDefFoundError: org/eclipse/core/resources/IWorkspaceRunnable
  at OnTheFlyJavaCompiler2.<init>(OnTheFlyJavaCompiler2.java:48)
  at OnTheFlyJavaCompiler2.class(OnTheFlyJavaCompiler2.java:37)
  at CompilationTestHelper.javaCompiler(CompilationTestHelper.java:157)
      \_ for field javaCompiler
  at XtendCompilerTester.compilationTestHelper(XtendCompilerTester.java:43)
      \_ for field compilationTestHelper
  while locating XtendCompilerTester

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
CompilationTestHelper: "org.eclipse.xtext.xbase.testing.CompilationTestHelper"
OnTheFlyJavaCompiler2: "org.eclipse.xtext.xbase.testing.OnTheFlyJavaCompiler2"
XtendCompilerTester:   "org.eclipse.xtend.core.compiler.batch.XtendCompilerTester"
========================
End of classname legend:
========================

	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186)
	at org.eclipse.xtend.core.compiler.batch.XtendCompilerTester.newXtendCompilerTester(XtendCompilerTester.java:56)
	at extract.ExtractTest.<init>(ExtractTest.java:28)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
	at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:530)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:758)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:453)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:211)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/core/resources/IWorkspaceRunnable
	at org.eclipse.xtext.xbase.testing.InMemoryJavaCompiler.findInlineJsrBytecode(InMemoryJavaCompiler.java:226)
	at org.eclipse.xtext.xbase.testing.InMemoryJavaCompiler.<clinit>(InMemoryJavaCompiler.java:223)
	at org.eclipse.xtext.xbase.testing.OnTheFlyJavaCompiler2.<init>(OnTheFlyJavaCompiler2.java:52)
	at org.eclipse.xtext.xbase.testing.OnTheFlyJavaCompiler2.<init>(OnTheFlyJavaCompiler2.java:48)
	at org.eclipse.xtext.xbase.testing.OnTheFlyJavaCompiler2$$FastClassByGuice$$1202bfea.GUICE$TRAMPOLINE(<generated>)
	at org.eclipse.xtext.xbase.testing.OnTheFlyJavaCompiler2$$FastClassByGuice$$1202bfea.apply(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
	... 30 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.core.resources.IWorkspaceRunnable
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 54 more



i hate this delete everything shit in platform :(

**Comment by LorenzoBettini** [comment]
> @LorenzoBettini wonder if we can archive the screenshots somehow if swtbot takes any

@cdietrich Yes, see for example https://github.com/LorenzoBettini/edelta/blob/master/.github/workflows/maven.yml#L67

To be honest, I thought we already archived screenshots in Xtext itself, but maybe we never needed to.

**Comment by LorenzoBettini** [comment]
@cdietrich when it happened in the past in my projects, that was due to some changed transitive/re-exported dependencies. Explicitly adding the dep used to work for me.

**Comment by cdietrich** [comment]
dm example still does not work :(

**Comment by cdietrich** [comment]
```
java.lang.IllegalArgumentException: Java code compiled with errors:
Pb(0) SANITY CHECK: Invalid opcode -88 at pc 156 for stackmap table attribute for method doStuff()

Code was:
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;
import org.eclipse.xtext.xbase.lib.util.ToStringBuilder;

@SuppressWarnings("all")
public class Foo {
  public Foo() {
  }

  public Foo(final Procedure1<Foo> initializer) {
    initializer.apply(this);
  }

  public Object doStuff() {
    String _xtrycatchfinallyexpression = null;
    try {
      _xtrycatchfinallyexpression = "MyString";
    } finally {
      "bla".length();
    }
    return ((String) _xtrycatchfinallyexpression);
  }

  @Override
  public String toString() {
    String result = new ToStringBuilder(this).addAllFields().toString();
    return result;
  }
}

	at org.eclipse.xtext.xbase.testing.OnTheFlyJavaCompiler2.compileToClass(OnTheFlyJavaCompiler2.java:92)
	at org.eclipse.xtext.example.domainmodel.tests.XbaseIntegrationTest.invokeXbaseExpression(XbaseIntegrationTest.java:59)
	at org.eclipse.xtext.xbase.testing.evaluation.AbstractXbaseEvaluationTest.assertEvaluatesTo(AbstractXbaseEvaluationTest.java:5346)
	at org.eclipse.xtext.xbase.testing.evaluation.AbstractXbaseEvaluationTest.testCastedExpression_06(AbstractXbaseEvaluationTest.java:2967)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.eclipse.xtext.testing.XtextRunner$1.evaluate(XtextRunner.java:50)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)


```

**Comment by cdietrich** [comment]
@szarnekow any idea?

**Comment by cdietrich** [comment]
wonder why the patch for 
https://github.com/eclipse/xtext/issues/3188
is not working. maybe we cannot determine version :(

**Comment by cdietrich** [comment]
java.lang.NullPointerException: Cannot invoke "org.eclipse.core.runtime.Plugin.getBundle()" because the return value of "org.eclipse.jdt.core.JavaCore.getPlugin()" is null
	at org.eclipse.xtext.xbase.testing.InMemoryJavaCompiler.findInlineJsrBytecode(InMemoryJavaCompiler.java:226)
	at org.eclipse.xtext.xbase.testing.InMemoryJavaCompiler.<clinit>(InMemoryJavaCompiler.java:223)
	at org.eclipse.xtext.xbase.testing.OnTheFlyJavaCompiler2.<init>(OnTheFlyJavaCompiler2.java:52)
	at org.eclipse.xtext.xbase.testing.OnTheFlyJavaCompiler2.<init>(OnTheFlyJavaCompiler2.java:48)
	at org.eclipse.xtext.xbase.testing.OnTheFlyJavaCompiler2$$FastClassByGuice$$11bb94bc.GUICE$TRAMPOLINE(<generated>)
	at org.eclipse.xtext.xbase.testing.OnTheFlyJavaCompiler2$$FastClassByGuice$$11bb94bc.apply(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)

of course this CRAPPPPPPPPP
does not work in standalone mode
=> no version check possible.

=> check if setter is there. if yes invoke it :(

**Comment by LorenzoBettini** [comment]
Or in this case, catch the NPE?

**Comment by LorenzoBettini** [comment]
Moreover, we should have a test for the on the fly compiler.
I thought we had some...

**Comment by szarnekow** [comment]
I think we do have tests but those are often executed as plugin tests, no?

**Comment by cdietrich** [comment]
yes

**Comment by LorenzoBettini** [comment]
But that should be the case for domainmodel as well, during a Maven build.
But maybe, @cdietrich, you're referring to the case when running from Eclipse as a plain JUnit test, aren't you?

**Comment by cdietrich** [comment]
yes this is what the swt bot tests in xtext-reference-projects/integrationtests do.
they create projects and do eclipse interactions with it

**Comment by cdietrich** [comment]
with 2nd fix it seems to work
